FROM node:22-alpine AS build
WORKDIR /app
COPY ca.crt /ca.crt
ENV NODE_EXTRA_CA_CERTS=/ca.crt HTTPS_PROXY=http://127.0.0.1:33337 HTTP_PROXY=http://127.0.0.1:33337 NO_PROXY=localhost,127.0.0.1
COPY package*.json .npmrc ./
RUN npm ci
COPY . .
RUN npx ng build

FROM nginx:1.27-alpine
COPY security-headers.inc /etc/nginx/security-headers.inc
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/web/browser /usr/share/nginx/html
EXPOSE 80
