import { launch, step, loginAs, openProject, tab } from './lib.mjs';
import { seedTenant, seedProject } from './seed.mjs';
const u = await seedTenant('d-' + Date.now().toString(36));
const proj = await seedProject(u);
const { b, p, errors } = await launch();
p.on('dialog', d => d.accept(d.message().includes('ETC') ? '150000' : '复检合格，有效'));

await loginAs(p, u.pm); await openProject(p, proj.code);
await tab(p, '成本');
await p.fill('input[formcontrolname=code]', 'MAT');
await p.fill('input[formcontrolname=name]', '材料');
await p.fill('input[formcontrolname=budget]', '600000');
await p.click('button:has-text("添加成本科目")');
await p.waitForSelector('td:has-text("MAT")'); step('添加成本科目');
await p.fill('input[formcontrolname=budget]', '600000');
await p.fill('input[formcontrolname=code]', 'OVER'); await p.fill('input[formcontrolname=name]', '超额');
await p.click('button:has-text("添加成本科目")');
await p.waitForSelector('text=各成本科目预算之和超过了项目预算'); step('预算分配超额被拦截');
await p.click('mat-select[formcontrolname=accountId]'); await p.click('mat-option:has-text("MAT")');
await p.fill('input[formcontrolname=amount]', '500000');
await p.fill('input[formcontrolname=description]', '钢材采购');
await p.click('button:has-text("记录成本")');
await p.waitForSelector('td:has-text("钢材采购")'); step('记录实际成本');
await p.click('button:has-text("调整尚需")');
await p.waitForSelector('td.over'); step('ETC 调整后科目预警（偏差标红）');

await tab(p, '质量计划');
await p.fill('textarea[formcontrolname=objectives]', '一次交检合格率 ≥ 98%');
await p.fill('textarea[formcontrolname=activities]', 'QA | 过程审核 | 每月\nQC | 焊缝无损检测 | 每批');
await p.click('button:has-text("保存计划")');
await p.waitForSelector('h2:has-text("第 1 版，未批准")'); step('保存质量计划');
await tab(p, '质量与不符合项');
await p.fill('input[formcontrolname=title]', '焊缝气孔');
await p.fill('input[formcontrolname=description]', '构架焊缝发现气孔');
await p.click('button:has-text("登记不符合项")');
await p.waitForSelector('.box:has-text("NC-001")'); step('登记不符合项');

await tab(p, '沟通与培训');
await p.fill('textarea[formcontrolname=channels]', '客户 | 周报邮件 | 每周');
await p.click('button:has-text("保存沟通计划")');
await p.waitForSelector('h2:has-text("第 1 版")');
await p.fill('input[formcontrolname=subject]', '交期沟通');
await p.fill('input[formcontrolname=summary]', '客户同意顺延两周');
await p.click('button:has-text("登记")');
await p.waitForSelector('.box:has-text("交期沟通")'); step('沟通计划与记录');

// 质量经理批准质量计划并推进不符合项
await loginAs(p, u.pqm); await openProject(p, proj.code); await tab(p, '质量计划');
await p.click('button:has-text("质量经理批准")');
await p.waitForSelector('h2:has-text("已批准")'); step('质量经理批准质量计划');
await tab(p, '质量与不符合项');
await p.click('.box button:has-text("开始原因分析")');
await p.waitForSelector('.box:has-text("原因分析")');
await p.fill('.box input[formcontrolname=containment]', '隔离并全检');
await p.fill('.box input[formcontrolname=rootCause]', '保护气流量偏低');
await p.fill('.box input[formcontrolname=correctiveAction]', '更换流量计');
await p.click('.box mat-select[formcontrolname=actionOwnerId]'); await p.click('mat-option:has-text("王成员")');
await p.fill('.box input[formcontrolname=actionDueDate]', '2026-04-01');
await p.click('.box button:has-text("保存")');
await p.waitForSelector('.box:has-text("根本原因：保护气流量偏低")');
await p.click('.box button:has-text("进入措施执行")');
await p.waitForSelector('.box:has-text("措施执行")');
await p.click('.box button:has-text("措施完成，提交验证")');
await p.waitForSelector('.box:has-text("有效性验证")');
await p.click('.box button:has-text("验证有效并关闭")');
await p.waitForSelector('.box:has-text("已关闭")'); step('不符合项完成闭环');
await p.screenshot({ path: `${process.env.SHOT_DIR ?? '/tmp'}/quality.png` });
console.log('浏览器错误:', errors.length ? errors : '无');
await b.close();
