import { launch, step, loginAs, openProject, tab } from './lib.mjs';
import { seedTenant, seedProject } from './seed.mjs';
const slug = 'c-' + Date.now().toString(36);
const u = await seedTenant(slug);
const proj = await seedProject(u);
const { b, p, errors } = await launch();
p.on('dialog', d => d.accept(d.message().includes('授权') ? '客户催交，风险已评估' : '有效：预算已更新'));

// 1. 关口评审
await loginAs(p, u.pm); await openProject(p, proj.code);
await tab(p, '关口评审');
await p.click('button:has-text("发起关口评审")');
await p.waitForSelector('text=评审进行中'); step('发起关口评审');
await p.click('mat-checkbox:has-text("设计评审完成")');
await p.click('mat-select[formcontrolname=attendees]');
await p.click('mat-option:has-text("李经理")'); await p.keyboard.press('Escape');
await p.click('mat-select[formcontrolname=decision]'); await p.click('mat-option:has-text("通过")');
await p.fill('input[formcontrolname=note]', '设计评审通过');
await p.click('button:has-text("记录评审结论")');
await p.waitForSelector('text=历史评审记录'); 
await p.waitForSelector('.phase:has-text("设计"):has-text("通过")'); step('评审通过并写入历史记录');
await p.waitForSelector('.phase.active:has-text("2. 制造")'); step('下一阶段自动启动');

// 2. 变更控制：预算增加 → 最高管理层批准 → 实施 → 验证 → 关闭
await tab(p, '变更控制');
await p.click('mat-select[formcontrolname=type]'); await p.click('mat-option:has-text("预算")');
await p.fill('input[formcontrolname=title]', '追加外协预算');
await p.fill('input[formcontrolname=budget]', '1200000');
await p.fill('textarea[formcontrolname=description]', '追加外协费用');
await p.fill('textarea[formcontrolname=reason]', '供应商涨价');
await p.fill('textarea[formcontrolname=impactAnalysis]', '成本增加 20 万，利润率下降 2%');
await p.click('button:has-text("保存为草稿")');
await p.waitForSelector('.cr:has-text("CR-001")'); step('创建变更草稿');
await p.click('.cr button:has-text("提交审批")');
await p.waitForSelector('.cr:has-text("待审批")'); step('提交审批');
await p.click('button:has-text("退出")');
await loginAs(p, u.top); await openProject(p, proj.code); await tab(p, '变更控制');
await p.click('.cr button:has-text("批准")');
await p.waitForSelector('.cr:has-text("已批准")'); step('最高管理层批准预算增加');
await loginAs(p, u.pm); await openProject(p, proj.code); await tab(p, '变更控制');
await p.click('.cr button:has-text("实施")');
await p.waitForSelector('.cr:has-text("已实施")'); step('项目经理实施');
if (await p.locator('.cr button:has-text("验证有效性")').count()) throw new Error('实施人不应看到验证按钮');
step('实施人看不到验证按钮');
await loginAs(p, u.pqm); await openProject(p, proj.code); await tab(p, '变更控制');
await p.click('.cr button:has-text("验证有效性")');
await p.waitForSelector('.cr:has-text("已验证")'); step('质量经理验证有效性');
await loginAs(p, u.pm); await openProject(p, proj.code); await tab(p, '变更控制');
await p.click('.cr button:has-text("关闭")');
await p.waitForSelector('.cr:has-text("已关闭")'); step('关闭变更');
await p.click('.cr button:has-text("变更记录")');
await p.waitForSelector('.hist:has-text("changeRequest.close")'); step('变更记录完整');
await tab(p, '概览');
await p.waitForSelector('dd:has-text("1,200,000")'); step('预算已更新为 1200000');

// 3. 风险、问题、项目评审
await tab(p, '风险与机会');
await p.fill('input[formcontrolname=title]', '关键供应商延期');
await p.fill('input[formcontrolname=exposureAmount]', '200000');
await p.fill('input[formcontrolname=responseCost]', '30000');
await p.fill('input[formcontrolname=costBenefitAnalysis]', '提前下单可避免大部分损失');
await p.click('button:has-text("登记")');
await p.waitForSelector('td:has-text("关键供应商延期")');
await p.waitForSelector('text=应对划算'); step('风险登记并给出成本收益判断');
await tab(p, '问题与行动');
await p.fill('input[formcontrolname=title]', '图纸版本冲突');
await p.click('button:has-text("登记")');
await p.waitForSelector('td:has-text("图纸版本冲突")'); step('登记问题');
await tab(p, '项目评审');
await p.waitForSelector('text=评审准备：当前绩效');
await p.click('mat-select[formcontrolname=attendees]');
await p.click('mat-option:has-text("李经理")'); await p.keyboard.press('Escape');
await p.fill('textarea[formcontrolname=notes]', '月度评审');
await p.click('button:has-text("记录项目评审")');
await p.waitForSelector('.box:has-text("月度评审")'); step('记录项目评审');
await p.screenshot({ path: `${process.env.SHOT_DIR ?? '/tmp'}/review.png` });
console.log('浏览器错误:', errors.length ? errors : '无');
await b.close();
