/**
 * 中文 → 英文词典，供 I18n 服务在界面切换到英文时使用。
 * 匹配顺序：整句精确匹配 → 正则规则（动态拼接的句子）→ 按词条长度从长到短逐个替换。
 * 新增界面文字时，把中文原文和英文译文加到这里即可。
 */
export const EN_PHRASES: [string, string][] = [
  // 第 4 步：会议与公告
  ["会议", "Meetings"], ["公告", "Announcements"], ["+ 发起会议", "+ New meeting"], ["发起会议", "New meeting"], ["编辑会议", "Edit meeting"], ["会议类型", "Meeting type"], ["普通会议", "Meeting"], ["例会", "Regular meeting"], ["阶段评审会", "Phase review meeting"], ["项目评审会", "Project review meeting"], ["项目总结会", "Project closing meeting"], ["主题", "Subject"], ["开始", "Start"], ["结束", "End"], ["地点", "Location"], ["线上链接", "Online link"], ["重复", "Repeat"], ["每周", "Weekly"], ["每两周", "Every two weeks"], ["每月", "Monthly"], ["议程（每行一项）", "Agenda (one item per line)"], ["议程", "Agenda"], ["会前资料", "Pre-reading"], ["项目组参会人", "Project attendees"], ["外部参会人", "External attendees"], ["+ 外部人员", "+ External person"], ["从干系人添加…", "Add from stakeholders…"], ["组织者", "Organizer"], ["发送通知", "Send invitation"], ["再次发送通知", "Resend invitation"], ["参会确认", "Attendance"], ["纪要", "Minutes"], ["未发通知", "Not sent"], ["已通知", "Invited"], ["已发布纪要", "Minutes published"], ["待你确认", "Awaiting your reply"], ["参加", "Attend"], ["不参加", "Decline"], ["未回复", "No reply"], ["下载日历文件", "Download calendar file"], ["生成下一次", "Create next meeting"], ["取消会议", "Cancel meeting"], ["登记确认方式…", "Record confirmation…"], ["提醒未回复", "Remind non-responders"], ["上次未关闭的行动项（自动带出）", "Open actions from previous meetings"], ["讨论要点", "Discussion points"], ["决定事项", "Decisions"], ["+ 添加行动项", "+ Add action"], ["保存草稿", "Save draft"], ["发布纪要", "Publish minutes"], ["+ 发布公告", "+ New announcement"], ["发布公告", "New announcement"], ["全项目组", "Whole project team"], ["指定人员", "Selected people"], ["要求已读确认", "Require read confirmation"], ["无需确认", "No confirmation needed"], ["我已阅读", "I have read it"], ["你已确认阅读", "You confirmed reading"], ["提醒未读人员", "Remind unread"], ["已读", "Read"], ["未读", "Unread"], ["全部已读", "All read"],
  ["讨论", "Discussion"], ["还没有讨论。", "No discussion yet."], ["发表", "Post"], ["写下讨论内容，输入 @姓名 提到项目成员", "Write a comment; type @name to mention a project member"], ["邮件通知", "E-mail notifications"], ["待我处理", "Waiting for me"], ["近期会议", "Upcoming meetings"], ["我的行动项", "My actions"], ["我负责的工作包", "My work packages"], ["没有待处理的事项", "Nothing waiting"], ["近两周没有会议", "No meetings in the next two weeks"], ["没有未关闭的行动项", "No open actions"], ["没有进行中的工作包", "No active work packages"], ["已逾期", "Overdue"], ["计划完成", "Planned finish"], ["已确认", "Confirmed"],
  // 第 3 步：采购计划、FAI、售后交接
  ["采购计划", "Purchasing plan"], ["批准采购计划", "Approve purchasing plan"], ["重新批准", "Re-approve"], ["已修订，待重新批准", "Revised, awaiting re-approval"], ["修订后需重新批准", "Revisions need re-approval"], ["物料清单", "Material list"], ["物料", "Material"], ["供应商", "Supplier"], ["需求日期", "Need date"], ["最晚下单", "Order by"], ["长周期", "Long lead"], ["长周期物料", "Long-lead items"], ["到货", "Received"], ["结算", "Settle"], ["下单", "Order"], ["未下单", "Not ordered"], ["已下单", "Ordered"], ["部分到货", "Partly received"], ["已到货", "Received"], ["已取消", "Cancelled"], ["已结算", "Settled"], ["逾期未下单", "Overdue, not ordered"], ["需关注", "Attention"], ["显示已取消", "Show cancelled"], ["+ 新增物料", "+ Add material"], ["成本科目", "Cost account"], ["量产准备评审会自动检查", "Automatic checks for the series-production readiness review"], ["新建 FAI 记录", "New FAI record"], ["FAI 记录", "FAI records"], ["报告编号", "Report no."], ["产品 / 零件号", "Product / part no."], ["结论", "Result"], ["有条件通过", "Conditional pass"], ["不通过", "Fail"], ["遗留项", "Open points"], ["报告存放位置", "Report location"], ["保存 FAI 记录", "Save FAI record"], ["售后交接", "After-sales handover"], ["交接日期", "Handover date"], ["移交人", "Handed over by"], ["接收人", "Receiver"], ["外部接收人", "External receiver"], ["质保期自", "Warranty from"], ["移交文档", "Documents handed over"], ["遗留问题", "Open issues"], ["发起交接", "Start handover"], ["确认接收", "Confirm receipt"], ["未发起", "Not started"], ["已交接", "Handed over"],
  // 第三步 5C：项目绩效评价
  ["项目绩效评价", "Project performance evaluation"], ["绩效评价单", "Evaluation sheets"], ["权限受控", "Restricted"], ["按企业设置的可见范围显示", "Shown according to the company visibility settings"], ["导出评价单", "Export sheets"], ["项目经理", "Project manager"], ["方面", "Aspect"], ["权重", "Weight"], ["目标", "Target"], ["实际", "Actual"], ["得分", "Score"], ["综合", "Overall"], ["预计", "Estimated"], ["保存本项目权重", "Save project weights"], ["恢复企业默认权重", "Restore company weights"], ["+ 本项目自定义方面", "+ Project-specific aspect"], ["实际交付（入库）日期", "Actual delivery (goods-in) date"], ["管理层评语", "Management comment"], ["调整分数", "Adjusted score"], ["保存调整", "Save adjustment"], ["确认项目经理绩效", "Confirm project manager evaluation"], ["项目成员", "Project members"], ["参考数据", "Reference data"], ["等级", "Grade"], ["评语", "Comment"], ["已提交", "Submitted"], ["撤回修改", "Reopen"], ["全部提交并发送人事、部门", "Submit all and send to HR and departments"], ["工作质量", "Work quality"], ["按时完成", "On-time delivery"], ["协作配合", "Collaboration"], ["主动性", "Initiative"], ["优秀", "Excellent"], ["良好", "Good"], ["合格", "Satisfactory"], ["待改进", "Needs improvement"], ["项目经理绩效", "Project manager performance"], ["项目成员评价", "Member evaluations"], ["评价人", "Evaluator"], ["提交日期", "Submitted on"], ["确认日期", "Confirmed on"], ["导出 Excel", "Export Excel"], ["筛选", "Filter"], ["部门与负责人", "Departments & heads"], ["部门", "Department"], ["负责人", "Head"], ["添加部门", "Add department"], ["还没有部门", "No departments yet"], ["评价方面与权重", "Aspects & weights"], ["计分规则", "Scoring rules"], ["成员评价维度（1–5 分）", "Member dimensions (1–5)"], ["可见范围", "Visibility"], ["保存绩效评价设置", "Save evaluation settings"], ["+ 自定义方面", "+ Custom aspect"], ["管理层评分", "Scored by management"], ["自动", "Automatic"], ["人事", "HR"],
  // 第三步 5B：目标与风险
  ["目标与风险", "Objectives & risks"], ["企业风险", "Enterprise risks"], ["项目目标", "Project objectives"], ["+ 自定义目标", "+ Custom objective"], ["风险与机会登记", "Risk & opportunity register"], ["识别 → 评价 → 应对策划", "Identify → assess → plan response"], ["点描述查看应对、复评和关闭", "Click a description for response, re-assessment and closing"], ["企业级", "Enterprise"], ["项目级", "Project"], ["工作包级", "Work package"], ["影响目标", "Objective"], ["重要度", "Importance"], ["策略", "Strategy"], ["措施", "Measures"], ["下次复查", "Next review"], ["未策划", "Not planned"], ["显示已关闭", "Show closed"], ["识别", "Identified"], ["应对中", "Mitigating"], ["待复评", "Awaiting re-assessment"], ["已发生", "Occurred"], ["已关闭", "Closed"], ["正常", "On track"], ["关注", "Watch"], ["偏离", "Off track"], ["未开始", "Not started"], ["打开的风险", "Open risks"], ["预警", "Warnings"], ["没有预警。", "No warnings."], ["1 识别", "1 Identify"], ["2 评价", "2 Assess"], ["3 应对", "3 Respond"], ["4 预警", "4 Warn"], ["5 复评与关闭", "5 Re-assess & close"], ["描述", "Description"], ["层级", "Level"], ["后果", "Consequence"], ["影响的项目目标", "Affected objective"], ["关联工作包", "Work package"], ["责任人", "Owner"], ["受影响的项目", "Affected projects"], ["所有层级的风险在企业内公开可见", "Risks at every level are visible across the company"], ["应对策略", "Response strategy"], ["应对成本（元）", "Response cost"], ["成本收益分析", "Cost-benefit analysis"], ["接受的理由", "Reason for accepting"], ["应急预案", "Contingency plan"], ["确认接受", "Confirm acceptance"], ["管理层已确认", "Confirmed by management"], ["+ 添加措施", "+ Add measure"], ["还没有措施", "No measures yet"], ["预警条件", "Trigger condition"], ["复查周期（天）", "Review cycle (days)"], ["预警条件已触发，通知相关人", "Trigger condition met — notify"], ["系统自动预警", "Automatic warnings"], ["记录复查", "Record review"], ["复查记录", "Review history"], ["复评并关闭", "Re-assess & close"], ["风险已发生，转为问题", "Risk occurred — raise issue"], ["关闭说明", "Closing note"], ["评价矩阵", "Assessment matrix"], ["影响判断标准", "Impact criteria"], ["审批、关闭、通知和复查规则", "Approval, closing, notification and review rules"], ["风险管理", "Risk management"], ["保存风险管理设置", "Save risk settings"], ["应对审批", "Response approval"], ["关闭确认", "Closing confirmation"], ["通知", "Notify"], ["项目经理", "Project manager"], ["管理层", "Management"], ["写明理由", "Reason"], ["理由 + 应急预案", "Reason + contingency plan"], ["理由 + 应急预案 + 管理层确认", "Reason + contingency plan + management confirmation"], ["消除", "Avoid"], ["转移", "Transfer"], ["减弱", "Mitigate"], ["接受", "Accept"], ["利用", "Exploit"], ["分享", "Share"], ["提高", "Enhance"], ["企业级风险与机会", "Enterprise risks & opportunities"], ["未关闭", "Open"],
  // 第三步 5A：成本与质量
  ["成本策划", "Cost planning"], ["质量策划", "Quality planning"], ["检验记录", "Inspection records"], ["工作包超支", "Work package overruns"], ["承诺成本", "Commitments"], ["成本科目", "Cost accounts"], ["工作包预算", "Work package budgets"], ["科目预算", "Account budget"], ["工作包合计", "Work package total"], ["未分配", "Unallocated"], ["按工作包合计设定科目预算", "Set account budgets from work packages"], ["建默认科目", "Create default accounts"], ["计划批准时检查", "Checks at plan approval"], ["超支怎么提醒", "How overruns are flagged"], ["人工", "Labour"], ["材料", "Material"], ["外协", "Subcontract"], ["工装", "Tooling"], ["试验", "Testing"], ["差旅", "Travel"], ["其他", "Other"], ["人天", "person-days"], ["元/人天", "CNY/person-day"], ["手工", "Manual"], ["预算（策划）", "Budget (plan)"], ["执行", "Execution"], ["实际发生", "Actual"], ["还需多少", "Estimate to complete"], ["预计完工", "Estimate at completion"], ["预算内", "Within budget"], ["保存预算", "Save budget"], ["+ 材料 / 外协 / 其他费用", "+ Material / subcontract / other"], ["时间", "Schedule"], ["成本", "Cost"], ["质量", "Quality"], ["关键", "Key"], ["结果", "Result"], ["记录", "Record"], ["待检", "Pending"], ["合格", "Pass"], ["不合格", "Fail"], ["不适用", "N/A"], ["开不符合项", "Raise nonconformity"], ["已开不符合项", "Nonconformity raised"], ["+ 添加检验项", "+ Add inspection item"], ["从检验项库添加…", "Add from inspection library…"], ["检验 / 验证项", "Inspection / verification items"], ["工作包上的检验 / 验证项", "Inspection items on work packages"], ["质量目标与标准", "Quality objectives & standards"], ["一次合格率", "First-pass yield"], ["验证人", "Verifier"], ["要求 / 准则", "Requirement / criterion"], ["需要的记录", "Required record"], ["方法", "Method"], ["类别", "Category"], ["检验项库", "Inspection library"], ["添加到库", "Add to library"], ["职能角色费率", "Functional role rates"], ["检验 / 验证项类别", "Inspection categories"], ["添加类别", "Add category"], ["登记", "Record"], ["项目总预算正常", "Project budget on track"],
  // 第二步：立项、项目要求、计划批准、模板
  ["立项管理", "Initiation"], ["+ 新建立项申请", "+ New initiation request"], ["新建立项申请", "New initiation request"], ["立项申请", "Initiation request"], ["立项申请批准后生成项目；项目要求的变更也在这里审批。", "Projects are created when an initiation request is approved; changes to project requirements are also approved here."], ["项目由立项申请批准后生成。", "Projects are created from approved initiation requests."], ["本企业开启了“小项目免立项”，也可以在下面直接建立小项目。", "“Small projects without initiation” is on, so small projects can also be created directly below."], ["默认（6 个阶段）", "Default (6 phases)"], ["项目类型", "Project type"], ["类型", "Type"], ["A 类 · 含产品设计开发", "Type A · with product design"], ["B 类 · 基于客户合同", "Type B · customer contract"], ["C 类 · 按库存计划", "Type C · stock plan"], ["客户合同 + 设计开发；FAI 必做", "Customer contract + design; FAI required"], ["不含设计开发；量产前技术准备；FAI 可选", "No design; technical preparation before series production; FAI optional"], ["无客户合同；以入库代替交付；FAI 可选", "No customer contract; goods-in instead of delivery; FAI optional"], ["全部", "All"], ["草稿", "Draft"], ["待会签", "Awaiting co-sign"], ["待审批", "Awaiting approval"], ["已批准", "Approved"], ["驳回", "Rejected"], ["已撤回", "Withdrawn"], ["项目要求变更", "Requirement change"], ["立项分类", "Initiation filter"], ["编号", "Code"], ["项目名称", "Project name"], ["申请人", "Applicant"], ["提交", "Submitted"], ["状态", "Status"], ["说明", "Notes"], ["暂无立项申请。", "No initiation requests."], ["已生成项目", "Project created"], ["会签已完成", "Co-sign complete"], ["查看", "View"], ["收起", "Hide"], ["原因", "Reason"], ["批准变更", "Approve change"], ["暂无项目要求变更。", "No requirement changes."], ["项目要求变更由项目经理在项目的「计划 → 项目要求与需求」里发起，立项批准人在这里审批。批准后生成新的项目要求版本，项目计划需要重新批准。", "Requirement changes are raised by the project manager under “Plan → Requirements” and approved here. Approval creates a new requirements version and the plan must be re-approved."], ["保存草稿", "Save draft"], ["提交审批", "Submit for approval"], ["基本信息", "Basic information"], ["项目编号", "Project code"], ["产品族", "Product family"], ["风险等级", "Risk level"], ["建议的项目经理", "Proposed project manager"], ["请选择", "Select"], ["计划开始日期", "Planned start"], ["客户", "Customer"], ["合同号", "Contract no."], ["合同金额（元）", "Contract amount"], ["项目要求", "Project requirements"], ["批准后项目内不能突破，只能通过“项目要求变更”修改", "Binding once approved; can only be changed through a requirement change"], ["提交前检查", "Pre-submission check"], ["审批路线", "Approval route"], ["会签", "Co-sign"], ["批准", "Approve"], ["生成项目", "Create project"], ["立项批准人；申请人不能批准自己的申请", "Initiation approver; applicants cannot approve their own request"], ["会签意见", "Co-sign opinions"], ["同意", "Agree"], ["不同意", "Disagree"], ["批准立项", "Approve initiation"], ["撤回申请", "Withdraw request"], ["打开生成的项目 →", "Open the created project →"], ["时间", "Schedule"], ["全部交付日期", "Final delivery date"], ["+ 添加关键节点", "+ Add milestone"], ["关键节点", "Milestone"], ["日期", "Date"], ["有长周期物料，需要提前订货", "Long-lead items need early ordering"], ["交付物", "Deliverables"], ["名称", "Name"], ["数量", "Quantity"], ["类别", "Category"], ["产品", "Product"], ["文件", "Document"], ["+ 添加交付物", "+ Add deliverable"], ["质量", "Quality"], ["适用标准（用顿号或逗号分隔）", "Applicable standards (comma-separated)"], ["验收方式", "Acceptance method"], ["特殊要求", "Special requirements"], ["做 FAI 首件鉴定", "First article inspection required"], ["客户见证 FAI / 批准首件", "Customer witnesses FAI / approves first article"], ["图纸须经客户审批", "Drawings require customer approval"], ["合同要求 RAMS 分析", "Contract requires RAMS analysis"], ["不做 FAI 的理由", "Reason for no FAI"], ["成本", "Cost"], ["成本上限（元）", "Cost cap"], ["目标成本（元）", "Target cost"], ["初步风险与机会", "Initial risks & opportunities"], ["风险", "Risk"], ["机会", "Opportunity"], ["内容", "Content"], ["+ 添加风险或机会", "+ Add risk or opportunity"], ["+ 添加库存计划行", "+ Add stock-plan line"], ["要求入库日期", "Required goods-in date"], ["C 类按库存计划入库，最后一行的日期即全部入库日期。", "Type C follows the stock plan; the last line’s date is the final goods-in date."], ["计划批准", "Plan approval"], ["细化需求", "Detailed requirements"], ["计划检查", "Plan check"], ["通过", "Passed"], ["未通过", "Not passed"], ["提交批准", "Submit for approval"], ["项目经理提交", "Project manager submits"], ["检查全部通过才能提交", "All checks must pass first"], ["管理层批准", "Management approves"], ["计划批准人；立项批准人也可批准", "Plan approver; initiation approvers can also approve"], ["生效", "Effective"], ["保存为新一版计划，作为进度和成本的对比基准", "Saved as a new plan version, the baseline for schedule and cost"], ["提交计划批准", "Submit plan for approval"], ["批准计划", "Approve plan"], ["退回修改", "Return for rework"], ["历史版本", "Version history"], ["版本", "Version"], ["批准日期", "Approved on"], ["工作包", "Work packages"], ["本项目没有经过立项，由项目经理在「总览」里自行批准计划。下面的检查供参考。", "This project was not initiated; the project manager approves the plan under “Overview”. The checks below are for reference."], ["本项目没有经过立项（“小项目免立项”直接建立），没有项目要求版本；下面的细化需求照常使用。", "This project was created without initiation, so it has no requirements versions; detailed requirements below work as usual."], ["未通过的项需要先修改计划；如果确实做不到项目要求，请发起", "Fix the plan for failed items; if the project requirements truly cannot be met, raise a "], ["，不能在项目内直接放行。", "— they cannot be waived inside the project."], ["发起项目要求变更", "Raise requirement change"], ["变更原因", "Reason for change"], ["取消", "Cancel"], ["项目要求变更记录", "Requirement change history"], ["基于", "Based on"], ["审批意见", "Decision note"], ["修改", "Edit"], ["只能通过“项目要求变更”修改", "Changed only through a requirement change"], ["从可选库添加…", "Add from optional library…"], ["从可选工作包库添加", "Add from optional library"], ["放在哪个阶段下", "Place under phase"], ["（顶层）", "(top level)"], ["添加", "Add"], ["按角色指定责任人", "Assign owners by role"], ["按职能角色指定责任人", "Assign owners by functional role"], ["不指定", "Not assigned"], ["已有责任人的也改", "Also replace existing owners"], ["确定", "OK"], ["立项与审批角色", "Initiation & approval roles"], ["立项申请人", "Initiators"], ["会签人", "Co-signers"], ["立项批准人", "Initiation approvers"], ["计划批准人", "Plan approvers"], ["人员", "Person"], ["授权依据", "Authorization basis"], ["生效日", "Valid from"], ["失效日", "Valid to"], ["+ 添加人员", "+ Add person"], ["已保存", "Saved"], ["项目类型模板", "Project type templates"], ["可选工作包库", "Optional work-package library"], ["阶段与 WBS 模板", "Phase & WBS templates"], ["导出 Excel", "Export Excel"], ["导入 Excel", "Import Excel"], ["恢复默认", "Restore default"], ["系统默认", "System default"], ["工期", "Duration"], ["前置", "Predecessors"], ["责任角色", "Role"], ["交付物 / 记录", "Deliverable / record"], ["条件", "Condition"], ["里程碑", "Milestone"], ["新增", "Add"], ["工作包名称", "Work package name"], ["工期（工作日）", "Duration (working days)"], ["建议位置", "Suggested position"], ["交付物 / 记录", "Deliverable / record"], ["适用：", "Applies to:"], ["添加到库", "Add to library"], ["启用", "Activate"], ["立项", "Initiation"], ["立项需要会签（会签人全部签完意见才进入批准）", "Initiation requires co-sign (all co-signers sign before approval)"], ["小项目免立项（允许项目经理不经立项直接建项目，由项目经理自己批准计划）", "Small projects without initiation (project managers may create projects directly and approve their own plans)"], ["计划待重新批准", "Plan awaiting re-approval"], ["计划待批准", "Plan awaiting approval"], ["型式试验", "Type test"],
  // 底座调整：菜单、项目分组、职能角色、品牌、默认阶段
  ['我的工作台', 'My workbench'], ['资源', 'Resources'], ['模板', 'Templates'], ['知识库', 'Knowledge'], ['管理', 'Administration'], ['用户与角色', 'Users & roles'], ['审计', 'Audit'], ['总览', 'Overview'], ['执行', 'Execution'], ['控制', 'Control'], ['沟通', 'Communication'], ['收尾', 'Closing'], ['项目要求与需求', 'Requirements'], ['团队与职责', 'Team & responsibilities'], ['阶段与评审', 'Phases & reviews'], ['文档与配置', 'Documents & configuration'], ['沟通计划与干系人', 'Communication plan & stakeholders'], ['总结与关闭', 'Summary & closure'], ['项目分组', 'Project sections'], ['子页面', 'Sub-pages'], ['计划已批准', 'Plan approved'], ['品牌', 'Branding'], ['系统名称', 'System name'], ['系统名称显示在顶栏和浏览器标签上；企业名称显示在系统名称旁边。', 'The system name appears in the top bar and browser tab; the company name appears next to it.'], ['职能角色', 'Functional roles'], ['新角色名称', 'New role name'], ['新增角色', 'Add role'], ['角色名称', 'Role name'], ['用户数', 'Users'], ['停用', 'Inactive'], ['已有同名角色', 'A role with this name already exists'], ['新增失败', 'Could not add'], ['职能角色用于模板和计划里按角色指定责任人。模板和项目引用的是角色本身，改名后各处同步显示新名称。停用的角色不能再分配给用户。', 'Functional roles are used to assign owners by role in templates and plans. Templates and projects refer to the role itself, so a rename shows everywhere. Inactive roles cannot be assigned to users.'], ['工艺', 'Process engineering'], ['生产', 'Production'], ['物流', 'Logistics'], ['仓库', 'Warehouse'], ['售后', 'After-sales'], ['项目策划', 'Project planning'], ['技术准备', 'Technical preparation'], ['FAI 首件鉴定', 'First article inspection'], ['量产', 'Series production'], ['项目总结', 'Project summary'], ['项目要求已分解为需求清单', 'Project requirements broken down into a requirements list'], ['风险与机会已识别', 'Risks & opportunities identified'], ['客户图纸与技术文件已评审', 'Customer drawings and technical documents reviewed'], ['PFMEA 与控制计划已完成', 'PFMEA and control plan completed'], ['工艺文件与工装检具已就绪', 'Process documents, tooling and gauges ready'], ['首件检验已完成', 'First article inspected'], ['FAI 报告已出具', 'FAI report issued'], ['遗留问题已关闭或已有计划', 'Open points closed or planned'], ['采购计划已批准', 'Purchasing plan approved'], ['长周期物料已下单', 'Long-lead items ordered'], ['批量生产与出厂检验已完成', 'Series production and final inspection completed'], ['交付文件已准备', 'Delivery documents prepared'], ['客户已验收', 'Accepted by customer'], ['项目要求达成情况已评价', 'Achievement of project requirements evaluated'], ['售后交接已完成', 'Handover to after-sales completed'],
  ['主菜单', 'Main menu'], ['试验 / 检验 / 分析 / 评审', 'Test / inspection / analysis / review'],
  // 导航与通用
  ['首页', 'Home'], ['项目', 'Projects'], ['投标', 'Tenders'], ['经验教训库', 'Lessons learned'], ['阶段模板', 'Phase templates'],
  ['用户管理', 'Users'], ['审计日志', 'Audit log'], ['租户管理', 'Tenants'], ['退出', 'Log out'], ['欢迎，', 'Welcome, '],
  ['登录 Claude-PM', 'Log in to Claude-PM'], ['登录', 'Log in'], ['注册新企业', 'Register a new company'], ['创建企业并登录', 'Create company and log in'],
  ['已有账号，去登录', 'Already have an account? Log in'], ['企业标识', 'Company ID'], ['企业名称', 'Company name'], ['平台管理员留空', 'Leave empty for platform admins'],
  ['邮箱', 'Email'], ['密码（至少 8 位）', 'Password (min. 8 characters)'], ['密码', 'Password'], ['初始密码', 'Initial password'], ['管理员姓名', 'Admin name'], ['管理员邮箱', 'Admin email'],
  ['3–40 位小写字母、数字或连字符，登录时使用', '3–40 lowercase letters, digits or hyphens; used to log in'], ['格式不正确', 'Invalid format'],
  ['姓名', 'Name'], ['角色', 'Role'], ['启用', 'Enabled'], ['添加用户', 'Add user'], ['创建租户', 'Create tenant'], ['创建模板', 'Create template'],
  ['平台管理员', 'Platform admin'], ['企业管理员', 'Tenant admin'], ['最高管理层', 'Top management'], ['职能经理', 'Function manager'], ['项目质量经理', 'Project quality manager'],
  ['项目经理', 'Project manager'], ['工作包负责人', 'Work package owner'], ['成员（只读）', 'Member (read-only)'], ['成员', 'Members'],
  ['保存失败', 'Save failed'], ['创建失败', 'Create failed'], ['添加失败', 'Add failed'], ['更新失败', 'Update failed'], ['登记失败', 'Registration failed'], ['操作失败', 'Operation failed'],
  ['删除失败', 'Delete failed'], ['记录失败', 'Record failed'], ['关闭失败', 'Close failed'], ['上传失败', 'Upload failed'], ['批准失败', 'Approval failed'], ['授权失败', 'Authorization failed'],
  ['核验失败', 'Verification failed'], ['安排失败', 'Scheduling failed'], ['发起失败', 'Could not start'], ['转换失败', 'Conversion failed'], ['升版失败', 'Revision change failed'],
  ['建立基线失败', 'Baseline failed'], ['添加依赖失败', 'Add dependency failed'], ['登录失败，请稍后重试', 'Login failed, please try again later'],
  ['企业标识、邮箱或密码不正确', 'Incorrect company ID, email or password'], ['注册失败，请检查输入后重试', 'Registration failed, please check your input'],
  ['企业标识已被占用', 'Company ID is already taken'], ['企业标识已存在', 'Company ID already exists'], ['该邮箱已存在', 'This email already exists'],
  ['当前部署未开放自助注册，请联系平台管理员', 'Self-registration is disabled, please contact the platform admin'],
  ['没有权限执行此操作', 'You do not have permission for this action'], ['记录不存在或无权访问', 'Record not found or no access'], ['文件太大', 'File is too large'],
  ['信息不完整', 'Information incomplete'], ['加载更多', 'Load more'], ['保存', 'Save'], ['删除', 'Delete'], ['添加', 'Add'], ['登记', 'Register'], ['关闭', 'Close'],
  ['搜索', 'Search'], ['操作', 'Action'], ['状态', 'Status'], ['名称', 'Name'], ['编号', 'No.'], ['类型', 'Type'], ['类别', 'Category'], ['描述', 'Description'], ['说明', 'Notes'],
  ['时间', 'Time'], ['对象', 'Object'], ['操作人', 'Actor'], ['已删除用户', 'Deleted user'], ['系统', 'System'], ['无', 'None'], ['是', 'Yes'], ['否', 'No'],
  ['记录只增不改，数据库层禁止修改和删除。', 'Records are append-only; the database forbids updates and deletes.'],
  ['请从左侧进入', 'Please choose'], ['列表', 'List'], ['视图', 'View'], ['收起', 'Collapse'], ['收起记录', 'Hide history'], ['选择文件', 'Choose file'], ['上传', 'Upload'], ['下载', 'Download'],
  ['文档名称（同名则生成新版本）', 'Document name (same name creates a new version)'], ['版本说明', 'Version note'], ['目录', 'Folder'],
  // 项目
  ['项目编号', 'Project code'], ['项目名称', 'Project name'], ['风险等级', 'Risk level'], ['开始日期', 'Start date'], ['结束日期', 'End date'], ['预算', 'Budget'], ['阶段模板', 'Phase template'],
  ['默认（轨道交通 7 阶段）', 'Default (7 railway phases)'], ['暂不指定', 'Not now'], ['创建项目', 'Create project'], ['暂无可见的项目。', 'No visible projects.'],
  ['策划中', 'Planning'], ['执行中', 'Active'], ['已关闭', 'Closed'], ['已取消', 'Cancelled'], ['已基线', 'baselined'], ['已建立基线', 'Baselined'], ['已基线）', ' baselined)'],
  ['低', 'Low'], ['中', 'Medium'], ['高', 'High'], ['项目周期', 'Project period'], ['周期', 'Period'], ['客户交期', 'Customer delivery date'], ['评审周期', 'Review interval'],
  ['概览与计划', 'Overview & plan'], ['阶段', 'Phases'], ['WBS 与进度', 'WBS & schedule'], ['关口评审', 'Gate reviews'], ['项目评审', 'Project reviews'], ['变更控制', 'Change control'],
  ['风险与机会', 'Risks & opportunities'], ['问题与行动', 'Issues & actions'], ['成本', 'Cost'], ['质量与不符合项', 'Quality & nonconformities'], ['沟通与培训', 'Communication & training'],
  ['文档', 'Documents'], ['配置管理', 'Configuration'], ['经验教训与关闭', 'Lessons & closure'], ['交付物', 'Deliverables'],
  ['建立基线并启动项目', 'Baseline and start project'], ['策划完成后建立基线。此后范围、预算和客户交期的修改必须经过已批准的变更申请。', 'Create the baseline when planning is done. Afterwards, changes to scope, budget and customer delivery date need an approved change request.'],
  ['项目管理计划（第', 'Project management plan (version '], ['项目目标', 'Project objectives'], ['框架条件与假设', 'Frame conditions & assumptions'], ['范围排除项', 'Scope exclusions'],
  ['职责与权限', 'Responsibilities & authorities'], ['项目执行规则', 'Project execution rules'], ['保存计划', 'Save plan'], ['已保存', 'Saved'], ['概览', 'Overview'],
  ['必选参与者：', 'Mandatory participants: '], ['关口清单：', 'Gate checklist: '], ['未开始', 'Not started'], ['进行中', 'In progress'], ['无', 'None'],
  ['项目角色', 'Project role'], ['任命书编号', 'Appointment letter no.'], ['任命书', 'Appointment'], ['能力要求 / 培训', 'Competencies / training'], ['能力要求', 'Competencies'],
  ['变更委员会成员', 'Change control board member'], ['添加成员', 'Add member'], ['在项目中', 'On project'], ['用户', 'User'],
  // WBS
  ['上级', 'Parent'], ['（顶层）', '(top level)'], ['顶层）', 'top level)'], ['工期（天）', 'Duration (days)'], ['负责人', 'Owner'], ['未分配', 'Unassigned'], ['添加工作包', 'Add work package'],
  ['前置', 'Predecessor'], ['后续（完成后才能开始）', 'Successor (starts after predecessor)'], ['添加依赖', 'Add dependency'], ['甘特图', 'Gantt'], ['看板', 'Board'],
  ['编号', 'No.'], ['工期', 'Duration'], ['计划', 'Plan'], ['进度', 'Progress'], ['进度百分比', 'Progress percent'], ['核验', 'Verify'], ['已核验', 'Verified'], ['已完成', 'Done'],
  ['表示在关键路径上。', 'marks the critical path.'], ['关键路径', 'Critical path'], ['开始', 'Start'], ['完成', 'Finish'], ['标记完成', 'Mark done'],
  ['总工期', 'Total duration'], ['天，预计完成', ' days, projected finish '], ['（超出项目计划结束日', '(exceeds planned end date '], ['天）', ' days)'], ['天。', ' days.'], ['天', ' days'],
  ['暂无工作包，添加工作包和依赖后这里会显示甘特图与关键路径。', 'No work packages yet. The Gantt chart and critical path appear after you add work packages and dependencies.'],
  ['非关键（有浮动时间） 深色为已完成进度', 'Non-critical (has float). Dark part = completed progress'], ['非关键（有浮动时间）', 'Non-critical (has float)'],
  // 交付物
  ['添加交付物', 'Add deliverable'], ['所属阶段', 'Phase'], ['供方 / 责任方', 'Supplier / owner'], ['责任方', 'Owner'], ['到期日', 'Due date'], ['到期', 'Due'],
  ['内部交付物', 'Internal deliverable'], ['需客户批准', 'Needs customer approval'], ['外部供方交付物', 'External provider deliverable'], ['客户提供物', 'Customer-supplied item'],
  ['计划中', 'Planned'], ['已提交', 'Submitted'], ['已接受', 'Accepted'], ['被拒绝', 'Rejected'], ['不指定', 'Unspecified'],
  // 关口 / 评审 / 问题
  ['发起关口评审', 'Start gate review'], ['评审进行中', 'Review in progress'], ['出席者', 'Attendees'], ['保存清单与出席者', 'Save checklist & attendees'],
  ['最高管理层授权：带遗留问题通过', 'Top management authorization: pass with open issues'], ['已获最高管理层授权（', 'Authorized by top management ('],
  ['评审结论', 'Decision'], ['通过', 'Approved'], ['有条件通过（需行动计划）', 'Conditionally approved (action plan required)'], ['有条件通过', 'Conditionally approved'], ['拒绝', 'Rejected'],
  ['结论说明', 'Decision note'], ['行动计划（每行一项）', 'Action plan (one per line)'], ['记录评审结论', 'Record decision'], ['历史评审记录', 'Review history'], ['暂无已完成的评审。', 'No completed reviews yet.'],
  ['（已升级）', ' (escalated)'], ['已升级）', ' escalated)'], ['最高管理层授权通过）', ' approved by top management authorization)'],
  ['项目建立基线并启动后，才能进行阶段关口评审。', 'Gate reviews are available after the project is baselined and started.'],
  ['关口就绪情况：清单未通过', 'Gate readiness: checklist items failed '], ['项；未核验工作包', '; unverified work packages '], ['个；未接受交付物', '; unaccepted deliverables '], ['个；此前遗留的未关闭问题', '; open issues from earlier reviews '],
  ['评审准备：当前绩效', 'Review preparation: current performance'], ['计划进度', 'Planned progress'], ['实际进度', 'Actual progress'], ['偏差', 'Variance'], ['预计完工', 'Projected finish'], ['预计超期', 'Projected to overrun'],
  ['评审日期', 'Review date'], ['出席者（须含项目经理）', 'Attendees (must include the project manager)'], ['上报给', 'Report to'], ['不上报', 'Do not report'], ['评审纪要', 'Minutes'],
  ['需决策 / 升级事项', 'Items for decision / escalation'], ['行动项（每行一项）', 'Action items (one per line)'], ['记录项目评审', 'Record project review'], ['历史评审', 'Past reviews'],
  ['升级事项：', 'Escalation: '], ['已上报）', ' reported)'], ['尚未进行项目评审。评审周期：', 'No project review yet. Review interval: '], ['未关闭问题 / 行动项', 'Open issues / actions'], ['个）；未关闭风险 / 机会', ' overdue); open risks / opportunities '],
  ['问题 / 行动项', 'Issue / action'], ['问题', 'Issue'], ['行动项', 'Action'], ['来源', 'Source'], ['关口评审', 'Gate review'], ['风险应对', 'Risk response'], ['手工登记', 'Manual'], ['未关闭', 'Open'], ['已关闭：', 'Closed: '],
  ['请填写关闭结论', 'Enter the closing conclusion'], ['请填写授权理由（将记入审计日志）', 'Enter the reason for authorization (recorded in the audit log)'],
  // 变更
  ['提交变更申请', 'Submit change request'], ['变更申请', 'Change requests'], ['变更内容', 'Change description'], ['变更原因', 'Reason for change'], ['影响分析（含风险与机会）', 'Impact analysis (incl. risks & opportunities)'],
  ['原因分析（由故障引起时必填）', 'Cause analysis (required for failure-triggered changes)'], ['由故障 / 不合格引起', 'Triggered by failure / nonconformity'], ['保存为草稿', 'Save as draft'],
  ['范围', 'Scope'], ['客户交期', 'Customer delivery date'], ['技术', 'Technical'], ['其他', 'Other'], ['新预算', 'New budget'], ['新客户交期', 'New customer delivery date'], ['新结束日期', 'New end date'],
  ['草稿', 'Draft'], ['待审批', 'Pending approval'], ['已批准', 'Approved'], ['已驳回', 'Rejected'], ['已实施', 'Implemented'], ['已验证', 'Verified'],
  ['对已交付部件的影响', 'Impact on delivered parts'], ['对客户规格与配置的影响', 'Impact on customer specification & configuration'], ['需更新的文件', 'Documents to update'], ['技术要求再评估', 'Re-evaluation of technical requirements'], ['再验证活动', 'Re-validation activities'],
  ['原因：', 'Reason: '], ['影响分析：', 'Impact analysis: '], ['拟变更：', 'Proposed: '], ['预算 ', 'Budget '], ['客户交期 ', 'Customer delivery '], ['开始 ', 'Start '], ['结束 ', 'End '],
  ['已通知客户：', 'Customer notified: '], ['客户同意：', 'Customer agreed: '], ['审批意见：', 'Approval note: '], ['有效性验证：', 'Effectiveness check: '], ['审批意见', 'Approval note'],
  ['提交审批', 'Submit for approval'], ['记录已通知客户', 'Record: customer notified'], ['记录客户已同意', 'Record: customer agreed'], ['批准', 'Approve'], ['驳回', 'Reject'], ['实施', 'Implement'],
  ['验证有效性', 'Verify effectiveness'], ['变更记录', 'Change history'], ['收起记录', 'Hide history'], ['暂无变更申请。', 'No change requests.'], ['驳回原因', 'Rejection reason'], ['有效性验证结论', 'Effectiveness conclusion'],
  ['项目已建立基线，此项修改需要先提交并批准变更申请', 'The project is baselined; this change needs an approved change request first'],
  // 风险
  ['可能性 1–5', 'Probability 1–5'], ['影响 1–5', 'Impact 1–5'], ['可能性 1', 'Probability 1'], ['影响 1', 'Impact 1'], ['潜在损失 / 收益金额', 'Potential loss / gain'], ['应对成本', 'Response cost'], ['成本收益分析', 'Cost-benefit analysis'],
  ['评分', 'Score'], ['期望价值 / 应对成本', 'Expected value / response cost'], ['应对行动', 'Response actions'], ['应对行动内容', 'Response action'], ['应对划算', 'Response pays off'], ['应对成本高于期望价值', 'Response costs more than expected value'],
  ['风险', 'Risk'], ['机会', 'Opportunity'], ['标题', 'Title'], ['未处理', 'Open'], ['应对中', 'Mitigating'], ['已发生', 'Occurred'], ['未完成 /', 'open /'], ['已完成', 'done'],
  // 成本
  ['科目编号', 'Account code'], ['科目名称', 'Account name'], ['科目预算', 'Account budget'], ['添加成本科目', 'Add cost account'], ['科目', 'Account'], ['金额（负数为冲销）', 'Amount (negative = reversal)'], ['日期', 'Date'],
  ['记录成本', 'Record cost'], ['预算偏差', 'Budget variance'], ['尚需（ETC）', 'ETC'], ['完工估算（EAC）', 'EAC'], ['实际', 'Actual'], ['调整尚需', 'Adjust ETC'], ['（人工）', ' (manual)'], ['人工）', 'manual)'],
  ['成本记录（只增不改，更正请录入负数冲销）', 'Cost entries (append-only; correct with a negative entry)'], ['项目预算', 'Project budget'], ['未设置', 'not set'], ['已分配', 'allocated'], ['未分配', 'unallocated'],
  ['请输入完工尚需成本（ETC）', 'Enter the estimate to complete (ETC)'], ['实际成本', 'Actual cost'], ['预计超支）', 'projected overrun)'], ['未关闭问题', 'Open issues'],
  ['各成本科目预算之和超过了项目预算，如需增加请先走预算变更', 'The cost accounts add up to more than the project budget. Use a budget change request to increase it.'],
  // 质量
  ['项目质量计划（第', 'Project quality plan (version '], ['质量目标', 'Quality objectives'], ['项目专用程序 / 表单', 'Project-specific procedures / forms'], ['质量活动（每行：QA 或 QC', 'Quality activities (one per line: QA or QC'],
  ['质量经理批准', 'Quality manager approval'], ['已批准', 'Approved'], ['未批准', 'Not approved'], ['不符合项 / 整改（CAR）', 'Nonconformities / corrective actions (CAR)'], ['严重程度', 'Severity'], ['轻微', 'Minor'], ['重大', 'Major'], ['严重', 'Critical'],
  ['检验', 'Inspection'], ['审核', 'Audit'], ['客户', 'Customer'], ['供方', 'Supplier'], ['登记不符合项', 'Register nonconformity'], ['暂无不符合项。', 'No nonconformities.'], ['已登记', 'Registered'],
  ['原因分析', 'Root cause analysis'], ['措施执行', 'Action in progress'], ['有效性验证', 'Effectiveness verification'], ['遏制措施：', 'Containment: '], ['根本原因：', 'Root cause: '], ['纠正措施：', 'Corrective action: '],
  ['遏制措施', 'Containment'], ['根本原因', 'Root cause'], ['纠正措施', 'Corrective action'], ['措施负责人', 'Action owner'], ['完成期限', 'Due date'], ['未指定', 'Unassigned'],
  ['开始原因分析', 'Start root cause analysis'], ['进入措施执行', 'Start corrective action'], ['措施完成，提交验证', 'Action done, submit for verification'], ['验证有效并关闭', 'Effective — close'], ['措施无效，退回', 'Not effective — send back'],
  ['退回原因', 'Reason for sending back'], ['发生了什么', 'What happened'], ['今后怎么做', 'What to do next time'], ['焊缝无损检测', 'Weld NDT'], ['过程审核', 'Process audit'], ['每批', 'per batch'], ['每月&#10', 'monthly&#10'],
  ['质量计划至少要包含一项质量保证（QA）和一项质量控制（QC）活动', 'The quality plan needs at least one QA and one QC activity'],
  // 沟通与培训
  ['沟通计划（第', 'Communication plan (version '], ['沟通渠道（每行：对象', 'Channels (one per line: audience'], ['保存沟通计划', 'Save communication plan'], ['沟通记录', 'Communication log'], ['会议', 'Meeting'], ['客户沟通', 'Customer communication'], ['供方沟通', 'Supplier communication'],
  ['内部沟通', 'Internal communication'], ['主题', 'Subject'], ['参与人', 'Participants'], ['纪要', 'Summary'], ['培训计划（能力要求见', 'Training plan (competencies: see '], ['人员', 'Person'], ['培训内容', 'Training'], ['安排培训', 'Schedule training'],
  ['待完成', 'Pending'], ['标记完成', 'Mark done'], ['周报邮件', 'weekly report email'], ['每周&#10', 'weekly&#10'], ['每两周', 'every two weeks'], ['例会', 'regular meeting'],
  // 文档 / 配置 / 教训
  ['暂无文档。文档按标准目录归档，每次上传生成新版本，历史版本不可修改或删除。', 'No documents yet. Documents are filed in standard folders; each upload creates a new version and old versions cannot be changed or deleted.'],
  ['历史版本', 'Version history'], ['下载此版本', 'Download this version'], ['字节）', ' bytes)'], ['字节', ' bytes'], ['配置管理', 'Configuration management'],
  ['添加配置项', 'Add configuration item'], ['序列号', 'Serial no.'], ['批次号', 'Batch no.'], ['序列号 / 批次', 'Serial / batch'], ['安全相关', 'Safety-related'], ['最低可更换单元', 'Lowest replaceable unit'], ['升版', 'Revise'], ['版本', 'Revision'],
  ['属性', 'Attributes'], ['硬件', 'Hardware'], ['软件', 'Software'], ['文件', 'Document'], ['工具', 'Tool'], ['基线与配置状态', 'Baselines & configuration status'], ['设计态', 'As-designed'], ['制造态', 'As-built'], ['维护态', 'As-maintained'],
  ['基线名称', 'Baseline name'], ['建立基线', 'Create baseline'], ['最近基线：', 'Latest baseline: '], ['尚未建立', 'none yet'], ['安全相关配置项', 'Safety-related items'], ['个；', '; '], ['新增', 'added'], ['版本变化', 'revision changes'],
  ['产品分解结构必须分解到最低可更换单元，以下末级项还未标记：', 'The product breakdown must reach the lowest replaceable unit. These leaf items are not marked yet: '],
  ['新版本号（当前', 'New revision (current '], ['变更申请 ID（基线前可留空）', 'Change request ID (optional before a baseline)'],
  ['经验教训与良好实践', 'Lessons learned & good practices'], ['经验教训', 'Lesson learned'], ['良好实践', 'Good practice'], ['教训', 'Lesson'], ['关闭项目', 'Close project'], ['建议：', 'Recommendation: '], ['来自', 'from'],
  ['汇总本企业所有项目的经验教训与良好实践，供投标和新项目策划参考。', 'All lessons learned and good practices of your company, for tenders and new project planning.'], ['没有匹配的记录。', 'No matching records.'],
  ['关闭前需：所有阶段已关闭、无未关闭的问题 / 行动项和不符合项、已登记经验教训。', 'To close: all phases closed, no open issues / actions or nonconformities, lessons learned registered.'],
  ['未登记经验教训时的原因说明', 'Reason if no lessons are registered'], ['暂不能关闭项目：', 'The project cannot be closed yet: '], ['质量经理', 'Quality manager'],
  // 投标
  ['投标管理', 'Tender management'], ['投标编号', 'Tender no.'], ['新建投标', 'New tender'], ['编制中', 'Drafting'], ['已中标', 'Won'], ['未中标', 'Lost'], ['编辑内容', 'Edit content'], ['客户需求', 'Customer requirements'],
  ['风险与机会评估', 'Risk & opportunity assessment'], ['组织知识输入（参考的经验教训）', 'Organizational knowledge input (lessons referenced)'], ['交付物策划（含成本）', 'Deliverables plan (incl. cost)'], ['合同执行资源计划', 'Resource plan for contract execution'],
  ['风险金额评估', 'Risk exposure'], ['成本测算', 'Cost estimate'], ['报价', 'Offer price'], ['批准报价', 'Approve offer'], ['标记中标', 'Mark won'], ['标记未中标', 'Mark lost'], ['转为项目', 'Convert to project'], ['查看项目', 'View project'],
  ['新项目编号', 'New project code'], ['项目开始日期（YYYY-MM-DD）', 'Project start date (YYYY-MM-DD)'], ['项目结束日期（YYYY-MM-DD）', 'Project end date (YYYY-MM-DD)'], ['投标信息不完整', 'Tender information incomplete'], ['模板名称', 'Template name'],
  ['未选择模板的项目使用默认的轨道交通 7 个阶段。每行一个阶段，格式：', 'Projects without a template use the default 7 railway phases. One phase per line, format: '], ['阶段（每行一个）', 'Phases (one per line)'], ['阶段名', 'Phase name'],
  ['关口清单项1；清单项2', 'checklist item 1; checklist item 2'], ['设计评审完成；输出已受控&#10', 'Design review done; outputs controlled&#10'], ['个', ''], ['项', ''], ['版', ''], ['第', ''],
  // 默认阶段与清单
  ['设计与开发', 'Design & development'], ['采购', 'Procurement'], ['制造', 'Manufacturing'], ['调试与验证', 'Commissioning & validation'], ['交付', 'Delivery'], ['质保期', 'Warranty'], ['设计', 'Design'],
  ['投标文件已评审', 'Tender documents reviewed'], ['风险与机会已评估', 'Risks & opportunities assessed'], ['报价已批准', 'Offer approved'], ['设计输入已确认', 'Design inputs confirmed'], ['设计评审已完成', 'Design review completed'],
  ['设计输出已受控', 'Design outputs controlled'], ['供方已评价', 'Suppliers evaluated'], ['采购合同已签订', 'Purchase contracts signed'], ['首件检验已通过', 'First article inspection passed'], ['过程控制计划已执行', 'Process control plan executed'],
  ['型式试验已完成', 'Type tests completed'], ['调试记录已归档', 'Commissioning records filed'], ['客户验收点已确认', 'Customer acceptance points confirmed'], ['交付文件已移交', 'Delivery documents handed over'],
  ['质保期问题已关闭', 'Warranty issues closed'], ['经验教训已登记', 'Lessons learned registered'], ['客户验收', 'Customer acceptance'],
  // 文档目录
  ['01-合同与投标', '01-Contract & tender'], ['02-项目计划', '02-Project plan'], ['03-设计与开发', '03-Design & development'], ['04-采购与供方', '04-Procurement & suppliers'], ['05-制造与检验', '05-Manufacturing & inspection'],
  ['06-评审记录', '06-Review records'], ['07-变更与配置', '07-Change & configuration'], ['08-交付与验收', '08-Delivery & acceptance'], ['09-质保与关闭', '09-Warranty & closure'], ['99-其他', '99-Other'],
  // 仪表盘与通知
  ['待办', 'To-do'], ['我的待办', 'My to-dos'], ['项目组合', 'Portfolio'], ['健康度', 'Health'], ['通知', 'Notifications'], ['全部已读', 'Mark all read'], ['暂无通知', 'No notifications'], ['暂无待办', 'Nothing to do'],
  ['导出审核证据包', 'Export audit evidence pack'], ['导出失败', 'Export failed'], ['语言', 'Language'], ['计划结束', 'Planned end'], ['逾期行动项', 'Overdue actions'], ['高分风险', 'High-score risks'], ['不符合项', 'Nonconformities'], ['待审批变更', 'Pending changes'],
  ['最近评审', 'Last review'], ['评审逾期', 'Review overdue'], ['当前阶段', 'Current phase'], ['正常', 'On track'], ['关注', 'Watch'], ['告警', 'Alert'], ['尚无评审', 'None yet'],
  ['金额', 'Amount'], ['频次）', 'frequency)'], ['频次', 'Frequency'], ['渠道', 'Channel'], ['名称', 'Name'],
  ['培训计划（能力要求见「成员」页）', 'Training plan (competencies: see the Members tab)'],
  ['QA | 过程审核 | 每月\nQC | 焊缝无损检测 | 每批', 'QA | Process audit | monthly\nQC | Weld NDT | per batch'],
  ['客户 | 周报邮件 | 每周\n供方 | 例会 | 每两周', 'Customer | weekly report email | weekly\nSupplier | regular meeting | every two weeks'],
  ['设计 | 设计评审完成；输出已受控\n交付 | 客户验收', 'Design | design review done; outputs controlled\nDelivery | customer acceptance'],
  ['策划与执行', 'Plan & execute'], ['评审与控制', 'Review & control'], ['成本、质量与记录', 'Cost, quality & records'], ['项目模块', 'Project modules'],
  // 标点收尾（放在最后，使用最短匹配）
  ['：', ': '], ['；', '; '], ['，', ', '], ['。', '. '], ['（', ' ('], ['）', ')'], ['、', ', '], ['！', '!'], ['？', '?'], ['·', '·'], ['→', '→'],
  ['轨道交通项目管理与质量协同平台', 'Railway project management and quality collaboration platform'], ['按 ISO 22163:2023 组织项目策划、关口评审、变更控制和不符合项闭环，审核时一键导出证据包。', 'Organize project planning, gate reviews, change control and nonconformity closure per ISO 22163:2023, and export an evidence pack in one click for audits.'],
  ['使用管理员分配的账号登录', 'Sign in with the account your administrator gave you'], ['创建企业并成为它的管理员', 'Create a company and become its administrator'],
  ['个人设置', 'Account settings'], ['修改密码', 'Change password'], ['当前密码', 'Current password'], ['新密码（至少 8 位）', 'New password (at least 8 characters)'], ['再次输入新密码', 'Repeat new password'],
  ['你的密码是管理员设置的，请先修改为只有你自己知道的密码，然后才能继续使用系统。', 'Your password was set by an administrator. Change it to one only you know before continuing.'],
  ['密码已修改。其他设备上的登录已失效。', 'Password changed. Sessions on other devices have been signed out.'], ['两次输入的新密码不一致', 'The new passwords do not match'],
  ['重置密码', 'Reset password'], ['确认重置', 'Confirm reset'], ['待本人改密', 'Must change password'], ['新建用户或重置密码后，本人首次登录必须修改密码。', 'After an account is created or its password reset, the user must change the password at next sign-in.'],
  ['当前密码不正确', 'Current password is incorrect'], ['新密码不能与当前密码相同', 'The new password must differ from the current one'], ['请先修改初始密码', 'Please change your initial password first'], ['尝试次数过多，请稍后再试', 'Too many attempts, please try again later'], ['修改失败', 'Change failed'], ['重置失败', 'Reset failed'],
  ['需求', 'Requirements'], ['未关联交付物', 'Not linked to a deliverable'], ['未验证', 'Not verified'], ['已验证', 'Verified'], ['不适用', 'N/A'],
  ['时间', 'Time'], ['商务', 'Commercial'], ['技术', 'Technical'], ['法规', 'Regulatory'], ['其他', 'Other'],
  ['计划已批准：新增或删除需求需要引用一项已批准的范围变更；修改验证状态不受限制。', 'The plan is approved: adding or deleting requirements needs an approved scope change; verification status can be updated freely.'],
  ['计划已批准：新增或删除工作包需要引用一项已批准的范围变更。', 'The plan is approved: adding or deleting work packages needs an approved scope change.'],
  ['依据的范围变更', 'Approved scope change'], ['（不引用）', '(none)'], ['暂无已批准的范围变更，请先在「变更控制」里提交并获批', 'No approved scope change yet — submit one in Change control first'],
  ['需求内容', 'Requirement'], ['类别', 'Category'], ['来源（合同条款、规格书章节）', 'Source (contract clause, spec section)'], ['验证方式', 'Verification method'],
  ['关联交付物', 'Deliverable'], ['暂不关联', 'Not linked'], ['未关联', 'Not linked'], ['添加需求', 'Add requirement'], ['来源', 'Source'],
  ['还没有登记需求。建议把合同和技术规格书里的要求逐条列出，并关联到负责交付的交付物。', 'No requirements yet. List each contract and specification requirement and link it to the deliverable that fulfils it.'],
  ['新增工作包', 'New work package'], ['所属阶段', 'Phase'], ['产出的交付物', 'Output deliverable'], ['无', 'None'], ['成本科目', 'Cost account'],
  ['资源估算（人天）', 'Resource estimate (person-days)'], ['外部供方（如由供方完成）', 'External provider (if done by a supplier)'], ['长周期物料', 'Long-lead item'], ['长周期', 'Long lead'],
  ['保存修改', 'Save changes'], ['编辑', 'Edit'], ['取消', 'Cancel'], ['预算', 'Budget'],
  ['计划批准', 'Plan approval'], ['阶段、WBS、依赖、成员、预算都确认后，批准计划并启动项目。', 'Once phases, WBS, dependencies, members and budget are confirmed, approve the plan and start the project.'],
  ['批准计划并启动项目', 'Approve plan and start project'], ['批准后：', 'After approval:'], ['项目状态变为“进行中”，第一个阶段开始；', 'the project becomes active and the first phase starts;'],
  ['系统保存当前计划的快照（第 1 版），作为以后计划与实际对比的依据；', 'a snapshot of the current plan (version 1) is saved as the reference for plan-versus-actual comparison;'],
  ['新增或删除工作包和需求、修改预算、项目日期和客户交期，都必须先有已批准的变更申请；', 'adding or deleting work packages and requirements, and changing the budget, project dates or customer delivery date all need an approved change request;'],
  ['批准不能撤销。', 'approval cannot be undone.'], ['确认批准', 'Confirm approval'], ['批准计划失败', 'Plan approval failed'], ['计划批准版本', 'Approved plan versions'],
  ['原因', 'Reason'], ['工作包', 'Work packages'], ['批准计划', 'Plan approved'], ['项目组织图', 'Project organization chart'],
  ['为每位成员指定向谁汇报，系统据此画出组织图。成员在「成员」标签里维护。', 'Set whom each member reports to; the chart is drawn from this. Members are managed on the Members tab.'],
  ['项目角色', 'Project role'], ['汇报给', 'Reports to'], ['（最高层）', '(top)'], ['还没有项目成员。', 'No project members yet.'],
  ['多场地或联合体（如适用）', 'Multiple sites or consortium (if applicable)'], ['工作分工与运作接口', 'Work split and operational interfaces'], ['各方的职责与权限', 'Responsibilities and authorities of each party'],
  ['沟通渠道（项目内部及与客户、相关方）', 'Communication channels (internal, customer and interested parties)'], ['适用的过程和成文信息', 'Applicable processes and documented information'],
  ['项目计划批准并启动后，才能进行阶段关口评审。', 'Gate reviews are available after the plan is approved and the project started.'], ['项目计划已批准，此项修改需要引用一项已批准的变更申请', 'The plan is approved; this change needs an approved change request'],
  ['（计划已批准）', ' (plan approved)'], [' · 计划已批准', ' · plan approved'], ['编辑草稿 ', 'Edit draft '], ['保存草稿', 'Save draft'], ['取消编辑', 'Cancel editing'],
  ['工作包（可选）', 'Work package (optional)'],
  ['质量', 'Quality'], ['成本', 'Cost'], ['交付物已接受', 'Deliverables accepted'], ['需求已覆盖', 'Requirements covered'], ['未关闭不符合项', 'Open nonconformities'],
  ['进度绩效指数 SPI', 'Schedule performance index SPI'], ['预计完工', 'Projected finish'], ['成本绩效指数 CPI', 'Cost performance index CPI'], ['完工估算', 'Estimate at completion'],
  ['无异常', 'No issues'], ['计划批准后才计算 SPI、CPI 和与计划的偏差。', 'SPI, CPI and plan variance are calculated after the plan is approved.'],
  ['挣值分析', 'Earned value analysis'], ['完工预算 BAC', 'Budget at completion BAC'], ['计划值 PV', 'Planned value PV'], ['到今天按计划应完成的工作量', 'Work planned to be done by today'],
  ['挣值 EV', 'Earned value EV'], ['实际已完成的工作量', 'Work actually done'], ['实际成本 AC', 'Actual cost AC'], ['进度指数 SPI = EV ÷ PV', 'Schedule index SPI = EV ÷ PV'], ['小于 1 表示落后', 'Below 1 means behind'],
  ['成本指数 CPI = EV ÷ AC', 'Cost index CPI = EV ÷ AC'], ['小于 1 表示超支', 'Below 1 means over budget'], ['完工估算 EAC', 'Estimate at completion EAC'], ['项目预算 ÷ CPI', 'Project budget ÷ CPI'], ['各科目估算之和', 'Sum of account estimates'],
  ['计划批准后开始计算。', 'Calculated after the plan is approved.'], ['工作包没有填预算，按工期把项目预算分摊到工作包。', 'Work packages have no budgets, so the project budget is spread by duration.'], ['按工作包预算计算。', 'Based on work package budgets.'],
  ['评审准备：质量、进度、成本', 'Review preparation: quality, schedule, cost'], ['进度与遗留事项', 'Progress and open items'], ['阶段评审起始 WBS 层级', 'Gate review starting WBS level'],
  ['本阶段交付物', 'Deliverables of this phase'], ['末级工作包', 'Leaf work packages'], ['已验证', 'Verified'], ['本阶段没有交付物。', 'No deliverables in this phase.'],
  ['本阶段还没有归属的工作包（在「WBS 与进度」里为工作包指定所属阶段）。', 'No work packages belong to this phase yet (assign phases on the WBS tab).'],
  ['企业设置', 'Company settings'], ['挣值预警阈值', 'Earned value alert thresholds'], ['关注（黄）线', 'Watch (amber) line'], ['告警（红）线', 'Alert (red) line'], ['告警线必须低于关注线', 'The red line must be below the amber line'],
  ['进度绩效指数（SPI）和成本绩效指数（CPI）等于 1 表示与计划一致。指数低于“关注”线时，项目的进度或成本显示为黄色；低于“告警”线时显示为红色。', 'SPI and CPI equal to 1 mean on plan. Below the watch line the schedule or cost shows amber; below the alert line it shows red.'],
  ['各科目完工估算之和', 'Sum of account estimates at completion'],
  ['导出 Excel', 'Export Excel'], ['下载导入模板', 'Download import template'], ['导入 Excel', 'Import Excel'], ['从 WBS 模板添加…', 'Add from WBS template…'], ['另存为 WBS 模板', 'Save as WBS template'],
  ['导入失败，表格没有写入任何数据。请修改后重新导入：', 'Import failed and nothing was written. Fix the sheet and import again:'], ['里程碑', 'Milestone'], ['工期（工作日）', 'Duration (working days)'],
  ['★ 表示在关键路径上，◆ 表示里程碑。工期按企业工作日历计算（工作日）。', '★ = on the critical path, ◆ = milestone. Durations are in working days per the company calendar.'],
  ['WBS 模板名称', 'WBS template name'], ['保存模板失败', 'Saving the template failed'], ['导出失败', 'Export failed'], ['下载失败', 'Download failed'], ['导入失败', 'Import failed'], ['添加失败', 'Add failed'],
  ['◆ 里程碑', '◆ Milestone'], ['资源负荷', 'Resource load'], ['起始日期', 'Start date'], ['周数', 'Weeks'], ['查询', 'Search'], ['人员', 'Person'],
  ['接近满负荷（80% 以上）', 'Near full (80%+)'], ['超负荷', 'Overloaded'], ['这段时间没有分配给个人的未完成工作包。', 'No unfinished work packages assigned to people in this period.'],
  ['按人汇总所有进行中项目里分配给他的工作包人天（没填人天的按全职投入计算），与每周的可用工作日对比。已完成的工作包不计入，未完成部分按剩余比例计算。', 'Person-days of work packages assigned to each person across active projects (full-time if no estimate), compared with available working days per week. Completed work is excluded; unfinished work counts by the remaining share.'],
  ['工作日历', 'Working calendar'], ['工作包的工期按工作日计算，计划日期会跳过非工作日。修改后，所有项目的排程会立即按新日历重新计算。', 'Work package durations are in working days and planned dates skip non-working days. Changes re-schedule all projects immediately.'],
  ['周一', 'Mon'], ['周二', 'Tue'], ['周三', 'Wed'], ['周四', 'Thu'], ['周五', 'Fri'], ['周六', 'Sat'], ['周日', 'Sun'],
  ['放假日（每行一个日期，如 2026-10-01）', 'Holidays (one date per line, e.g. 2026-10-01)'], ['调休上班日（周末补班，每行一个日期）', 'Make-up working days (weekend days worked, one per line)'], ['每周至少要有一个工作日', 'At least one working day per week is required'],
  ['标准 WBS 模板', 'Standard WBS templates'], ['在项目的「WBS 与进度」里点“另存为 WBS 模板”即可创建；新项目可以从模板一键带出工作包结构。', 'Create one with "Save as WBS template" on a project\'s WBS tab; new projects can then add the structure in one click.'],
  ['还没有 WBS 模板。', 'No WBS templates yet.'], ['可选参与者：', 'Optional participants: '],
  ['产品成熟度（与客户商定）', 'Product maturity (agreed with customer)'], ['参与评审的职能经理', 'Functional managers in the review'], ['可弥补预算损失的金额', 'Amount that can offset budget losses'],
  ['SWOT 评审（与客户、关键供方）', 'SWOT review (with customer and key suppliers)'], ['与客户和关键外部供方一起评审项目的优势、劣势、机会和威胁，形成需要跟进的行动。', 'Review strengths, weaknesses, opportunities and threats with the customer and key external providers, and agree follow-up actions.'],
  ['评审日期', 'Review date'], ['参加方（客户、供方及人员）', 'Participants (customer, suppliers, people)'], ['优势 S', 'Strengths'], ['劣势 W', 'Weaknesses'], ['机会 O', 'Opportunities'], ['威胁 T', 'Threats'],
  ['后续行动', 'Follow-up actions'], ['记录 SWOT 评审', 'Record SWOT review'], ['优势', 'Strengths'], ['劣势', 'Weaknesses'], ['威胁', 'Threats'],
  ['偏离通报', 'Deviation notices'], ['项目即将偏离目标（质量、进度、成本）时，记录向客户和相关方通报的影响与对策。', 'When the project is about to deviate from its objectives (quality, schedule, cost), record the impact and countermeasures communicated to the customer and interested parties.'],
  ['方面', 'Aspect'], ['通报日期', 'Notice date'], ['通报对象', 'Notified parties'], ['影响', 'Impact'], ['对策', 'Countermeasures'], ['记录偏离通报', 'Record deviation notice'], ['暂无偏离通报。', 'No deviation notices yet.'],
  ['干系人登记册', 'Stakeholder register'], ['姓名 / 岗位', 'Name / position'], ['单位', 'Organization'], ['在项目中的角色', 'Role in the project'], ['影响力', 'Influence'], ['关注度', 'Interest'],
  ['主要期望', 'Main expectations'], ['沟通方式与频次', 'Communication method and frequency'], ['添加干系人', 'Add stakeholder'], ['干系人', 'Stakeholder'], ['角色', 'Role'], ['沟通方式', 'Communication'],
  ['还没有登记干系人。', 'No stakeholders yet.'], ['高', 'High'], ['中', 'Medium'], ['低', 'Low'],
  ['项目周报', 'Weekly report'], ['← 返回项目', '← Back to project'], ['打印 / 另存为 PDF', 'Print / save as PDF'], ['总体状态', 'Overall status'], ['本周完成', 'Completed this week'],
  ['未来两周计划开始', 'Planned to start in the next two weeks'], ['变更', 'Changes'], ['主要风险与机会', 'Top risks and opportunities'], ['本周无变化', 'No changes this week'],
  ['有方面处于告警状态。如需向客户或相关方通报影响和对策，请在「沟通与培训」里记录偏离通报。', 'Some aspects are in alert. To notify the customer or interested parties of the impact and countermeasures, record a deviation notice on the Communication tab.'],
  ['选择 Excel 文件', 'Choose an Excel file'], ['从 WBS 模板添加', 'Add from WBS template'], ['如 TRL 7、已批量应用', 'e.g. TRL 7, in series use'], ['客户项目经理、业主代表……', 'Customer PM, owner representative…'],
];

/** 动态拼接的句子：优先于逐词替换，捕获数字和名称后重排 */
export const EN_RULES: [RegExp, string][] = [
  [/^(A|B|C) 类$/, 'Type $1'],
  [/^项目要求 v(\d+)$/, 'Project requirements v$1'],
  [/^对照项目要求 v(\d+) 的检查$/, 'Check against project requirements v$1'],
  [/^计划 v(\d+)$/, 'Plan v$1'],
  [/^(.+)（(\d+) 天）$/, '$1 ($2 days)'],
  [/^按客户交期 (\S+) 倒排：预计 (\S+) 完工，余量 (\d+) 个工作日。$/, 'Back-scheduled from customer date $1: projected finish $2, $3 working days of slack.'],
  [/^项目经理：已指定$/, 'Project manager: assigned'], [/^项目经理：还没有指定$/, 'Project manager: not assigned'],
  [/^责任人：全部已指定$/, 'Owners: all assigned'],
  [/^责任人：还有 (\d+) 个工作包未指定（(.+)）$/, 'Owners: $1 work packages unassigned ($2)'],
  [/^交期：预计完工 (\S+)，要求 (\S+)$/, 'Delivery: projected $1, required $2'],
  [/^交期：预计完工 (\S+)，要求 (\S+)，晚 (\d+) 个工作日$/, 'Delivery: projected $1, required $2, $3 working days late'],
  [/^交付物：(\d+) 项都已落实到阶段或工作包$/, 'Deliverables: all $1 assigned to a phase or work package'],
  [/^风险：已登记 (\d+) 项风险与机会$/, 'Risks: $1 risks & opportunities registered'],
  [/^工作包：还没有工作包$/, 'Work packages: none yet'],
  [/^成本：预算 (\S+) 元，上限 (\S+) 元$/, 'Cost: budget $1, cap $2'],
  [/^比批准的计划晚 (\d+) 个工作日$/, '$1 working days behind the approved plan'], [/^超负荷 (\d+) 周$/, 'Overloaded in $1 weeks'], [/^可用 (\d+)$/, 'Available $1'],
  [/^导入完成：新增 (\d+) 个、更新 (\d+) 个工作包，新增 (\d+) 个依赖。$/, 'Import done: $1 work packages added, $2 updated, $3 dependencies added.'],
  [/^项目周报：(.+)$/, 'Weekly report: $1'], [/^问题与行动（未关闭 (\d+) 个）$/, 'Issues and actions ($1 open)'],
  [/^对比基准：计划批准第 (\d+) 版。指数低于 (\S+) 为关注，低于 (\S+) 为告警。$/, 'Baseline: approved plan version $1. Index below $2 is watch, below $3 is alert.'],
  [/^基准：计划批准第 (\d+) 版。(.*)$/, 'Baseline: approved plan version $1. $2'],
  [/^(\d+) 个严重不符合项未关闭$/, '$1 critical nonconformities open'], [/^(\d+) 个重大不符合项未关闭$/, '$1 major nonconformities open'],
  [/^(\d+) 个交付物被退回$/, '$1 deliverables rejected'], [/^(\d+) 条需求未关联交付物$/, '$1 requirements not linked to a deliverable'],
  [/^(\d+) 个交付物逾期未接受$/, '$1 deliverables overdue'], [/^(\d+) 个已完成的工作包待验证$/, '$1 completed work packages awaiting verification'],
  [/^预计完工 (\S+) 晚于客户交期 (\S+)$/, 'Projected finish $1 is later than customer date $2'],
  [/^进度绩效指数 SPI (\S+) 低于 (\S+)$/, 'SPI $1 below $2'], [/^成本绩效指数 CPI (\S+) 低于 (\S+)$/, 'CPI $1 below $2'],
  [/^比批准的计划晚 (\d+) 天$/, '$1 days behind the approved plan'], [/^完工估算 (\S+) 超出预算 (\S+)$/, 'Estimate at completion $1 exceeds budget $2'],
  [/^比批准计划晚 (\d+) 个工作日$/, '$1 working days behind plan'], [/^比批准计划早 (\d+) 个工作日$/, '$1 working days ahead of plan'],
  [/^工作包（从第 (\d+) 级 WBS 起汇总）$/, 'Work packages (rolled up from WBS level $1)'], [/^第 (\d+) 级$/, 'Level $1'],
  [/^欢迎，(.+)$/, 'Welcome, $1'],
  [/^已重置 (.+) 的密码。请把临时密码告知本人，对方下次登录后需要修改。$/, 'Password for $1 has been reset. Give the temporary password to the user; they must change it at next sign-in.'],
  [/^总工期 (\d+) 天，预计完成 (\S+)/, 'Total duration $1 days, projected finish $2'],
  [/^项目管理计划（第 (\d+) 版）$/, 'Project management plan (version $1)'],
  [/^项目质量计划（第 (\d+) 版，(已批准|未批准)）$/, 'Project quality plan (version $1, $2)'],
  [/^沟通计划（第 (\d+) 版）$/, 'Communication plan (version $1)'],
  [/^(\d+)\. (.+?) · (未开始|进行中|已关闭)$/, '$1. $2 · $3'],
  [/^未关闭问题 \/ 行动项 (\d+) 个（逾期 (\d+) 个）；未关闭风险 \/ 机会 (\d+) 个$/, 'Open issues / actions $1 ($2 overdue); open risks / opportunities $3'],
  [/^(\d+) 个（逾期 (\d+) 个）$/, '$1 (overdue $2)'],
  [/^(\d+) 个$/, '$1'],
  [/^v(\d+)$/, 'v$1'],
  [/^预计完工 (\S+) 晚于计划 (\S+)$/, 'Projected finish $1 is later than planned $2'],
  [/^预计成本超出预算$/, 'Projected cost exceeds budget'],
  [/^(\d+) 个严重不符合项未关闭$/, '$1 critical nonconformities open'],
  [/^(\d+) 个重大不符合项未关闭$/, '$1 major nonconformities open'],
  [/^进度落后 (\d+) 个百分点$/, 'Behind schedule by $1 percentage points'],
  [/^(\d+) 个行动项逾期$/, '$1 overdue actions'],
  [/^(\d+) 个高分风险$/, '$1 high-score risks'],
  [/^项目评审逾期$/, 'Project review overdue'],
  [/^(\d+) 个成本科目预计超支$/, '$1 cost accounts projected to overrun'],
  [/^待审批变更 (\S+)：(.+)$/, 'Change $1 awaiting approval: $2'],
  [/^有一个进行中的关口评审待记录结论$/, 'A gate review is waiting for a decision'],
  [/^(问题|行动项)：(.+)$/, '$1: $2'],
  [/^执行纠正措施 (\S+)：(.+)$/, 'Carry out corrective action $1: $2'],
  [/^工作包 (\S+) (.+?)（(\d+)%）$/, 'Work package $1 $2 ($3%)'],
  [/^培训：(.+)$/, 'Training: $1'],
];
