/**
 * 中文 → 英文词典，供 I18n 服务在界面切换到英文时使用。
 * 匹配顺序：整句精确匹配 → 正则规则（动态拼接的句子）→ 按词条长度从长到短逐个替换。
 * 新增界面文字时，把中文原文和英文译文加到这里即可。
 */
export const EN_PHRASES: [string, string][] = [
  // 导航与通用
  ['首页', 'Home'], ['项目', 'Projects'], ['投标', 'Tenders'], ['经验教训库', 'Lessons learned'], ['阶段模板', 'Phase templates'],
  ['用户管理', 'Users'], ['审计日志', 'Audit log'], ['租户管理', 'Tenants'], ['退出', 'Log out'], ['欢迎，', 'Welcome, '],
  ['登录 Claude-PM', 'Log in to Claude-PM'], ['登录', 'Log in'], ['注册新企业', 'Register a new company'], ['创建企业并登录', 'Create company and log in'],
  ['已有账号，去登录', 'Already have an account? Log in'], ['企业标识', 'Company ID'], ['企业名称', 'Company name'], ['平台管理员留空', 'Leave empty for platform admins'],
  ['邮箱', 'Email'], ['密码（至少 8 位）', 'Password (min. 8 characters)'], ['密码', 'Password'], ['初始密码', 'Initial password'], ['管理员姓名', 'Admin name'], ['管理员邮箱', 'Admin email'],
  ['3–40 位小写字母、数字或连字符，登录时使用', '3–40 lowercase letters, digits or hyphens; used to log in'], ['格式不正确', 'Invalid format'],
  ['姓名', 'Name'], ['角色', 'Role'], ['启用', 'Enabled'], ['添加用户', 'Add user'], ['创建租户', 'Create tenant'], ['创建模板', 'Create template'],
  ['平台管理员', 'Platform admin'], ['企业管理员', 'Tenant admin'], ['最高管理层', 'Top management'], ['职能经理', 'Function manager'], ['项目质量经理', 'Project quality manager'],
  ['项目经理', 'Project manager'], ['工作包负责人', 'Work package owner'], ['成员（只读）', 'Member (read-only)'], ['成员', 'Members'],
  ['保存失败', 'Save failed'], ['创建失败', 'Create failed'], ['添加失败', 'Add failed'], ['更新失败', 'Update failed'], ['登记失败', 'Registration failed'], ['操作失败', 'Operation failed'],
  ['删除失败', 'Delete failed'], ['记录失败', 'Record failed'], ['关闭失败', 'Close failed'], ['上传失败', 'Upload failed'], ['批准失败', 'Approval failed'], ['授权失败', 'Authorization failed'],
  ['核验失败', 'Verification failed'], ['安排失败', 'Scheduling failed'], ['发起失败', 'Could not start'], ['转换失败', 'Conversion failed'], ['升版失败', 'Revision change failed'],
  ['建立基线失败', 'Baseline failed'], ['添加依赖失败', 'Add dependency failed'], ['登录失败，请稍后重试', 'Login failed, please try again later'],
  ['企业标识、邮箱或密码不正确', 'Incorrect company ID, email or password'], ['注册失败，请检查输入后重试', 'Registration failed, please check your input'],
  ['企业标识已被占用', 'Company ID is already taken'], ['企业标识已存在', 'Company ID already exists'], ['该邮箱已存在', 'This email already exists'],
  ['当前部署未开放自助注册，请联系平台管理员', 'Self-registration is disabled, please contact the platform admin'],
  ['没有权限执行此操作', 'You do not have permission for this action'], ['记录不存在或无权访问', 'Record not found or no access'], ['文件太大', 'File is too large'],
  ['信息不完整', 'Information incomplete'], ['加载更多', 'Load more'], ['保存', 'Save'], ['删除', 'Delete'], ['添加', 'Add'], ['登记', 'Register'], ['关闭', 'Close'],
  ['搜索', 'Search'], ['操作', 'Action'], ['状态', 'Status'], ['名称', 'Name'], ['编号', 'No.'], ['类型', 'Type'], ['类别', 'Category'], ['描述', 'Description'], ['说明', 'Notes'],
  ['时间', 'Time'], ['对象', 'Object'], ['操作人', 'Actor'], ['已删除用户', 'Deleted user'], ['系统', 'System'], ['无', 'None'], ['是', 'Yes'], ['否', 'No'],
  ['记录只增不改，数据库层禁止修改和删除。', 'Records are append-only; the database forbids updates and deletes.'],
  ['请从左侧进入', 'Please choose'], ['列表', 'List'], ['视图', 'View'], ['收起', 'Collapse'], ['收起记录', 'Hide history'], ['选择文件', 'Choose file'], ['上传', 'Upload'], ['下载', 'Download'],
  ['文档名称（同名则生成新版本）', 'Document name (same name creates a new version)'], ['版本说明', 'Version note'], ['目录', 'Folder'],
  // 项目
  ['项目编号', 'Project code'], ['项目名称', 'Project name'], ['风险等级', 'Risk level'], ['开始日期', 'Start date'], ['结束日期', 'End date'], ['预算', 'Budget'], ['阶段模板', 'Phase template'],
  ['默认（轨道交通 7 阶段）', 'Default (7 railway phases)'], ['暂不指定', 'Not now'], ['创建项目', 'Create project'], ['暂无可见的项目。', 'No visible projects.'],
  ['策划中', 'Planning'], ['执行中', 'Active'], ['已关闭', 'Closed'], ['已取消', 'Cancelled'], ['已基线', 'baselined'], ['已建立基线', 'Baselined'], ['已基线）', ' baselined)'],
  ['低', 'Low'], ['中', 'Medium'], ['高', 'High'], ['项目周期', 'Project period'], ['周期', 'Period'], ['客户交期', 'Customer delivery date'], ['评审周期', 'Review interval'],
  ['概览与计划', 'Overview & plan'], ['阶段', 'Phases'], ['WBS 与进度', 'WBS & schedule'], ['关口评审', 'Gate reviews'], ['项目评审', 'Project reviews'], ['变更控制', 'Change control'],
  ['风险与机会', 'Risks & opportunities'], ['问题与行动', 'Issues & actions'], ['成本', 'Cost'], ['质量与不符合项', 'Quality & nonconformities'], ['沟通与培训', 'Communication & training'],
  ['文档', 'Documents'], ['配置管理', 'Configuration'], ['经验教训与关闭', 'Lessons & closure'], ['交付物', 'Deliverables'],
  ['建立基线并启动项目', 'Baseline and start project'], ['策划完成后建立基线。此后范围、预算和客户交期的修改必须经过已批准的变更申请。', 'Create the baseline when planning is done. Afterwards, changes to scope, budget and customer delivery date need an approved change request.'],
  ['项目管理计划（第', 'Project management plan (version '], ['项目目标', 'Project objectives'], ['框架条件与假设', 'Frame conditions & assumptions'], ['范围排除项', 'Scope exclusions'],
  ['职责与权限', 'Responsibilities & authorities'], ['项目执行规则', 'Project execution rules'], ['保存计划', 'Save plan'], ['已保存', 'Saved'], ['概览', 'Overview'],
  ['必选参与者：', 'Mandatory participants: '], ['关口清单：', 'Gate checklist: '], ['未开始', 'Not started'], ['进行中', 'In progress'], ['无', 'None'],
  ['项目角色', 'Project role'], ['任命书编号', 'Appointment letter no.'], ['任命书', 'Appointment'], ['能力要求 / 培训', 'Competencies / training'], ['能力要求', 'Competencies'],
  ['变更委员会成员', 'Change control board member'], ['添加成员', 'Add member'], ['在项目中', 'On project'], ['用户', 'User'],
  // WBS
  ['上级', 'Parent'], ['（顶层）', '(top level)'], ['顶层）', 'top level)'], ['工期（天）', 'Duration (days)'], ['负责人', 'Owner'], ['未分配', 'Unassigned'], ['添加工作包', 'Add work package'],
  ['前置', 'Predecessor'], ['后续（完成后才能开始）', 'Successor (starts after predecessor)'], ['添加依赖', 'Add dependency'], ['甘特图', 'Gantt'], ['看板', 'Board'],
  ['编号', 'No.'], ['工期', 'Duration'], ['计划', 'Plan'], ['进度', 'Progress'], ['进度百分比', 'Progress percent'], ['核验', 'Verify'], ['已核验', 'Verified'], ['已完成', 'Done'],
  ['表示在关键路径上。', 'marks the critical path.'], ['关键路径', 'Critical path'], ['开始', 'Start'], ['完成', 'Finish'], ['标记完成', 'Mark done'],
  ['总工期', 'Total duration'], ['天，预计完成', ' days, projected finish '], ['（超出项目计划结束日', '(exceeds planned end date '], ['天）', ' days)'], ['天。', ' days.'], ['天', ' days'],
  ['暂无工作包，添加工作包和依赖后这里会显示甘特图与关键路径。', 'No work packages yet. The Gantt chart and critical path appear after you add work packages and dependencies.'],
  ['非关键（有浮动时间） 深色为已完成进度', 'Non-critical (has float). Dark part = completed progress'], ['非关键（有浮动时间）', 'Non-critical (has float)'],
  // 交付物
  ['添加交付物', 'Add deliverable'], ['所属阶段', 'Phase'], ['供方 / 责任方', 'Supplier / owner'], ['责任方', 'Owner'], ['到期日', 'Due date'], ['到期', 'Due'],
  ['内部交付物', 'Internal deliverable'], ['需客户批准', 'Needs customer approval'], ['外部供方交付物', 'External provider deliverable'], ['客户提供物', 'Customer-supplied item'],
  ['计划中', 'Planned'], ['已提交', 'Submitted'], ['已接受', 'Accepted'], ['被拒绝', 'Rejected'], ['不指定', 'Unspecified'],
  // 关口 / 评审 / 问题
  ['发起关口评审', 'Start gate review'], ['评审进行中', 'Review in progress'], ['出席者', 'Attendees'], ['保存清单与出席者', 'Save checklist & attendees'],
  ['最高管理层授权：带遗留问题通过', 'Top management authorization: pass with open issues'], ['已获最高管理层授权（', 'Authorized by top management ('],
  ['评审结论', 'Decision'], ['通过', 'Approved'], ['有条件通过（需行动计划）', 'Conditionally approved (action plan required)'], ['有条件通过', 'Conditionally approved'], ['拒绝', 'Rejected'],
  ['结论说明', 'Decision note'], ['行动计划（每行一项）', 'Action plan (one per line)'], ['记录评审结论', 'Record decision'], ['历史评审记录', 'Review history'], ['暂无已完成的评审。', 'No completed reviews yet.'],
  ['（已升级）', ' (escalated)'], ['已升级）', ' escalated)'], ['最高管理层授权通过）', ' approved by top management authorization)'],
  ['项目建立基线并启动后，才能进行阶段关口评审。', 'Gate reviews are available after the project is baselined and started.'],
  ['关口就绪情况：清单未通过', 'Gate readiness: checklist items failed '], ['项；未核验工作包', '; unverified work packages '], ['个；未接受交付物', '; unaccepted deliverables '], ['个；此前遗留的未关闭问题', '; open issues from earlier reviews '],
  ['评审准备：当前绩效', 'Review preparation: current performance'], ['计划进度', 'Planned progress'], ['实际进度', 'Actual progress'], ['偏差', 'Variance'], ['预计完工', 'Projected finish'], ['预计超期', 'Projected to overrun'],
  ['评审日期', 'Review date'], ['出席者（须含项目经理）', 'Attendees (must include the project manager)'], ['上报给', 'Report to'], ['不上报', 'Do not report'], ['评审纪要', 'Minutes'],
  ['需决策 / 升级事项', 'Items for decision / escalation'], ['行动项（每行一项）', 'Action items (one per line)'], ['记录项目评审', 'Record project review'], ['历史评审', 'Past reviews'],
  ['升级事项：', 'Escalation: '], ['已上报）', ' reported)'], ['尚未进行项目评审。评审周期：', 'No project review yet. Review interval: '], ['未关闭问题 / 行动项', 'Open issues / actions'], ['个）；未关闭风险 / 机会', ' overdue); open risks / opportunities '],
  ['问题 / 行动项', 'Issue / action'], ['问题', 'Issue'], ['行动项', 'Action'], ['来源', 'Source'], ['关口评审', 'Gate review'], ['风险应对', 'Risk response'], ['手工登记', 'Manual'], ['未关闭', 'Open'], ['已关闭：', 'Closed: '],
  ['请填写关闭结论', 'Enter the closing conclusion'], ['请填写授权理由（将记入审计日志）', 'Enter the reason for authorization (recorded in the audit log)'],
  // 变更
  ['提交变更申请', 'Submit change request'], ['变更申请', 'Change requests'], ['变更内容', 'Change description'], ['变更原因', 'Reason for change'], ['影响分析（含风险与机会）', 'Impact analysis (incl. risks & opportunities)'],
  ['原因分析（由故障引起时必填）', 'Cause analysis (required for failure-triggered changes)'], ['由故障 / 不合格引起', 'Triggered by failure / nonconformity'], ['保存为草稿', 'Save as draft'],
  ['范围', 'Scope'], ['客户交期', 'Customer delivery date'], ['技术', 'Technical'], ['其他', 'Other'], ['新预算', 'New budget'], ['新客户交期', 'New customer delivery date'], ['新结束日期', 'New end date'],
  ['草稿', 'Draft'], ['待审批', 'Pending approval'], ['已批准', 'Approved'], ['已驳回', 'Rejected'], ['已实施', 'Implemented'], ['已验证', 'Verified'],
  ['对已交付部件的影响', 'Impact on delivered parts'], ['对客户规格与配置的影响', 'Impact on customer specification & configuration'], ['需更新的文件', 'Documents to update'], ['技术要求再评估', 'Re-evaluation of technical requirements'], ['再验证活动', 'Re-validation activities'],
  ['原因：', 'Reason: '], ['影响分析：', 'Impact analysis: '], ['拟变更：', 'Proposed: '], ['预算 ', 'Budget '], ['客户交期 ', 'Customer delivery '], ['开始 ', 'Start '], ['结束 ', 'End '],
  ['已通知客户：', 'Customer notified: '], ['客户同意：', 'Customer agreed: '], ['审批意见：', 'Approval note: '], ['有效性验证：', 'Effectiveness check: '], ['审批意见', 'Approval note'],
  ['提交审批', 'Submit for approval'], ['记录已通知客户', 'Record: customer notified'], ['记录客户已同意', 'Record: customer agreed'], ['批准', 'Approve'], ['驳回', 'Reject'], ['实施', 'Implement'],
  ['验证有效性', 'Verify effectiveness'], ['变更记录', 'Change history'], ['收起记录', 'Hide history'], ['暂无变更申请。', 'No change requests.'], ['驳回原因', 'Rejection reason'], ['有效性验证结论', 'Effectiveness conclusion'],
  ['项目已建立基线，此项修改需要先提交并批准变更申请', 'The project is baselined; this change needs an approved change request first'],
  // 风险
  ['可能性 1–5', 'Probability 1–5'], ['影响 1–5', 'Impact 1–5'], ['可能性 1', 'Probability 1'], ['影响 1', 'Impact 1'], ['潜在损失 / 收益金额', 'Potential loss / gain'], ['应对成本', 'Response cost'], ['成本收益分析', 'Cost-benefit analysis'],
  ['评分', 'Score'], ['期望价值 / 应对成本', 'Expected value / response cost'], ['应对行动', 'Response actions'], ['应对行动内容', 'Response action'], ['应对划算', 'Response pays off'], ['应对成本高于期望价值', 'Response costs more than expected value'],
  ['风险', 'Risk'], ['机会', 'Opportunity'], ['标题', 'Title'], ['未处理', 'Open'], ['应对中', 'Mitigating'], ['已发生', 'Occurred'], ['未完成 /', 'open /'], ['已完成', 'done'],
  // 成本
  ['科目编号', 'Account code'], ['科目名称', 'Account name'], ['科目预算', 'Account budget'], ['添加成本科目', 'Add cost account'], ['科目', 'Account'], ['金额（负数为冲销）', 'Amount (negative = reversal)'], ['日期', 'Date'],
  ['记录成本', 'Record cost'], ['预算偏差', 'Budget variance'], ['尚需（ETC）', 'ETC'], ['完工估算（EAC）', 'EAC'], ['实际', 'Actual'], ['调整尚需', 'Adjust ETC'], ['（人工）', ' (manual)'], ['人工）', 'manual)'],
  ['成本记录（只增不改，更正请录入负数冲销）', 'Cost entries (append-only; correct with a negative entry)'], ['项目预算', 'Project budget'], ['未设置', 'not set'], ['已分配', 'allocated'], ['未分配', 'unallocated'],
  ['请输入完工尚需成本（ETC）', 'Enter the estimate to complete (ETC)'], ['实际成本', 'Actual cost'], ['预计超支）', 'projected overrun)'], ['未关闭问题', 'Open issues'],
  ['各成本科目预算之和超过了项目预算，如需增加请先走预算变更', 'The cost accounts add up to more than the project budget. Use a budget change request to increase it.'],
  // 质量
  ['项目质量计划（第', 'Project quality plan (version '], ['质量目标', 'Quality objectives'], ['项目专用程序 / 表单', 'Project-specific procedures / forms'], ['质量活动（每行：QA 或 QC', 'Quality activities (one per line: QA or QC'],
  ['质量经理批准', 'Quality manager approval'], ['已批准', 'Approved'], ['未批准', 'Not approved'], ['不符合项 / 整改（CAR）', 'Nonconformities / corrective actions (CAR)'], ['严重程度', 'Severity'], ['轻微', 'Minor'], ['重大', 'Major'], ['严重', 'Critical'],
  ['检验', 'Inspection'], ['审核', 'Audit'], ['客户', 'Customer'], ['供方', 'Supplier'], ['登记不符合项', 'Register nonconformity'], ['暂无不符合项。', 'No nonconformities.'], ['已登记', 'Registered'],
  ['原因分析', 'Root cause analysis'], ['措施执行', 'Action in progress'], ['有效性验证', 'Effectiveness verification'], ['遏制措施：', 'Containment: '], ['根本原因：', 'Root cause: '], ['纠正措施：', 'Corrective action: '],
  ['遏制措施', 'Containment'], ['根本原因', 'Root cause'], ['纠正措施', 'Corrective action'], ['措施负责人', 'Action owner'], ['完成期限', 'Due date'], ['未指定', 'Unassigned'],
  ['开始原因分析', 'Start root cause analysis'], ['进入措施执行', 'Start corrective action'], ['措施完成，提交验证', 'Action done, submit for verification'], ['验证有效并关闭', 'Effective — close'], ['措施无效，退回', 'Not effective — send back'],
  ['退回原因', 'Reason for sending back'], ['发生了什么', 'What happened'], ['今后怎么做', 'What to do next time'], ['焊缝无损检测', 'Weld NDT'], ['过程审核', 'Process audit'], ['每批', 'per batch'], ['每月&#10', 'monthly&#10'],
  ['质量计划至少要包含一项质量保证（QA）和一项质量控制（QC）活动', 'The quality plan needs at least one QA and one QC activity'],
  // 沟通与培训
  ['沟通计划（第', 'Communication plan (version '], ['沟通渠道（每行：对象', 'Channels (one per line: audience'], ['保存沟通计划', 'Save communication plan'], ['沟通记录', 'Communication log'], ['会议', 'Meeting'], ['客户沟通', 'Customer communication'], ['供方沟通', 'Supplier communication'],
  ['内部沟通', 'Internal communication'], ['主题', 'Subject'], ['参与人', 'Participants'], ['纪要', 'Summary'], ['培训计划（能力要求见', 'Training plan (competencies: see '], ['人员', 'Person'], ['培训内容', 'Training'], ['安排培训', 'Schedule training'],
  ['待完成', 'Pending'], ['标记完成', 'Mark done'], ['周报邮件', 'weekly report email'], ['每周&#10', 'weekly&#10'], ['每两周', 'every two weeks'], ['例会', 'regular meeting'],
  // 文档 / 配置 / 教训
  ['暂无文档。文档按标准目录归档，每次上传生成新版本，历史版本不可修改或删除。', 'No documents yet. Documents are filed in standard folders; each upload creates a new version and old versions cannot be changed or deleted.'],
  ['历史版本', 'Version history'], ['下载此版本', 'Download this version'], ['字节）', ' bytes)'], ['字节', ' bytes'], ['配置管理', 'Configuration management'],
  ['添加配置项', 'Add configuration item'], ['序列号', 'Serial no.'], ['批次号', 'Batch no.'], ['序列号 / 批次', 'Serial / batch'], ['安全相关', 'Safety-related'], ['最低可更换单元', 'Lowest replaceable unit'], ['升版', 'Revise'], ['版本', 'Revision'],
  ['属性', 'Attributes'], ['硬件', 'Hardware'], ['软件', 'Software'], ['文件', 'Document'], ['工具', 'Tool'], ['基线与配置状态', 'Baselines & configuration status'], ['设计态', 'As-designed'], ['制造态', 'As-built'], ['维护态', 'As-maintained'],
  ['基线名称', 'Baseline name'], ['建立基线', 'Create baseline'], ['最近基线：', 'Latest baseline: '], ['尚未建立', 'none yet'], ['安全相关配置项', 'Safety-related items'], ['个；', '; '], ['新增', 'added'], ['版本变化', 'revision changes'],
  ['产品分解结构必须分解到最低可更换单元，以下末级项还未标记：', 'The product breakdown must reach the lowest replaceable unit. These leaf items are not marked yet: '],
  ['新版本号（当前', 'New revision (current '], ['变更申请 ID（基线前可留空）', 'Change request ID (optional before a baseline)'],
  ['经验教训与良好实践', 'Lessons learned & good practices'], ['经验教训', 'Lesson learned'], ['良好实践', 'Good practice'], ['教训', 'Lesson'], ['关闭项目', 'Close project'], ['建议：', 'Recommendation: '], ['来自', 'from'],
  ['汇总本企业所有项目的经验教训与良好实践，供投标和新项目策划参考。', 'All lessons learned and good practices of your company, for tenders and new project planning.'], ['没有匹配的记录。', 'No matching records.'],
  ['关闭前需：所有阶段已关闭、无未关闭的问题 / 行动项和不符合项、已登记经验教训。', 'To close: all phases closed, no open issues / actions or nonconformities, lessons learned registered.'],
  ['未登记经验教训时的原因说明', 'Reason if no lessons are registered'], ['暂不能关闭项目：', 'The project cannot be closed yet: '], ['质量经理', 'Quality manager'],
  // 投标
  ['投标管理', 'Tender management'], ['投标编号', 'Tender no.'], ['新建投标', 'New tender'], ['编制中', 'Drafting'], ['已中标', 'Won'], ['未中标', 'Lost'], ['编辑内容', 'Edit content'], ['客户需求', 'Customer requirements'],
  ['风险与机会评估', 'Risk & opportunity assessment'], ['组织知识输入（参考的经验教训）', 'Organizational knowledge input (lessons referenced)'], ['交付物策划（含成本）', 'Deliverables plan (incl. cost)'], ['合同执行资源计划', 'Resource plan for contract execution'],
  ['风险金额评估', 'Risk exposure'], ['成本测算', 'Cost estimate'], ['报价', 'Offer price'], ['批准报价', 'Approve offer'], ['标记中标', 'Mark won'], ['标记未中标', 'Mark lost'], ['转为项目', 'Convert to project'], ['查看项目', 'View project'],
  ['新项目编号', 'New project code'], ['项目开始日期（YYYY-MM-DD）', 'Project start date (YYYY-MM-DD)'], ['项目结束日期（YYYY-MM-DD）', 'Project end date (YYYY-MM-DD)'], ['投标信息不完整', 'Tender information incomplete'], ['模板名称', 'Template name'],
  ['未选择模板的项目使用默认的轨道交通 7 个阶段。每行一个阶段，格式：', 'Projects without a template use the default 7 railway phases. One phase per line, format: '], ['阶段（每行一个）', 'Phases (one per line)'], ['阶段名', 'Phase name'],
  ['关口清单项1；清单项2', 'checklist item 1; checklist item 2'], ['设计评审完成；输出已受控&#10', 'Design review done; outputs controlled&#10'], ['个', ''], ['项', ''], ['版', ''], ['第', ''],
  // 默认阶段与清单
  ['设计与开发', 'Design & development'], ['采购', 'Procurement'], ['制造', 'Manufacturing'], ['调试与验证', 'Commissioning & validation'], ['交付', 'Delivery'], ['质保期', 'Warranty'], ['设计', 'Design'],
  ['投标文件已评审', 'Tender documents reviewed'], ['风险与机会已评估', 'Risks & opportunities assessed'], ['报价已批准', 'Offer approved'], ['设计输入已确认', 'Design inputs confirmed'], ['设计评审已完成', 'Design review completed'],
  ['设计输出已受控', 'Design outputs controlled'], ['供方已评价', 'Suppliers evaluated'], ['采购合同已签订', 'Purchase contracts signed'], ['首件检验已通过', 'First article inspection passed'], ['过程控制计划已执行', 'Process control plan executed'],
  ['型式试验已完成', 'Type tests completed'], ['调试记录已归档', 'Commissioning records filed'], ['客户验收点已确认', 'Customer acceptance points confirmed'], ['交付文件已移交', 'Delivery documents handed over'],
  ['质保期问题已关闭', 'Warranty issues closed'], ['经验教训已登记', 'Lessons learned registered'], ['客户验收', 'Customer acceptance'],
  // 文档目录
  ['01-合同与投标', '01-Contract & tender'], ['02-项目计划', '02-Project plan'], ['03-设计与开发', '03-Design & development'], ['04-采购与供方', '04-Procurement & suppliers'], ['05-制造与检验', '05-Manufacturing & inspection'],
  ['06-评审记录', '06-Review records'], ['07-变更与配置', '07-Change & configuration'], ['08-交付与验收', '08-Delivery & acceptance'], ['09-质保与关闭', '09-Warranty & closure'], ['99-其他', '99-Other'],
  // 仪表盘与通知
  ['待办', 'To-do'], ['我的待办', 'My to-dos'], ['项目组合', 'Portfolio'], ['健康度', 'Health'], ['通知', 'Notifications'], ['全部已读', 'Mark all read'], ['暂无通知', 'No notifications'], ['暂无待办', 'Nothing to do'],
  ['导出审核证据包', 'Export audit evidence pack'], ['导出失败', 'Export failed'], ['语言', 'Language'], ['计划结束', 'Planned end'], ['逾期行动项', 'Overdue actions'], ['高分风险', 'High-score risks'], ['不符合项', 'Nonconformities'], ['待审批变更', 'Pending changes'],
  ['最近评审', 'Last review'], ['评审逾期', 'Review overdue'], ['当前阶段', 'Current phase'], ['正常', 'On track'], ['关注', 'Watch'], ['告警', 'Alert'], ['尚无评审', 'None yet'],
  ['金额', 'Amount'], ['频次）', 'frequency)'], ['频次', 'Frequency'], ['渠道', 'Channel'], ['名称', 'Name'],
  ['培训计划（能力要求见「成员」页）', 'Training plan (competencies: see the Members tab)'],
  ['QA | 过程审核 | 每月\nQC | 焊缝无损检测 | 每批', 'QA | Process audit | monthly\nQC | Weld NDT | per batch'],
  ['客户 | 周报邮件 | 每周\n供方 | 例会 | 每两周', 'Customer | weekly report email | weekly\nSupplier | regular meeting | every two weeks'],
  ['设计 | 设计评审完成；输出已受控\n交付 | 客户验收', 'Design | design review done; outputs controlled\nDelivery | customer acceptance'],
  ['策划与执行', 'Plan & execute'], ['评审与控制', 'Review & control'], ['成本、质量与记录', 'Cost, quality & records'], ['项目模块', 'Project modules'],
  // 标点收尾（放在最后，使用最短匹配）
  ['：', ': '], ['；', '; '], ['，', ', '], ['。', '. '], ['（', ' ('], ['）', ')'], ['、', ', '], ['！', '!'], ['？', '?'], ['·', '·'], ['→', '→'],
];

/** 动态拼接的句子：优先于逐词替换，捕获数字和名称后重排 */
export const EN_RULES: [RegExp, string][] = [
  [/^欢迎，(.+)$/, 'Welcome, $1'],
  [/^总工期 (\d+) 天，预计完成 (\S+)/, 'Total duration $1 days, projected finish $2'],
  [/^项目管理计划（第 (\d+) 版）$/, 'Project management plan (version $1)'],
  [/^项目质量计划（第 (\d+) 版，(已批准|未批准)）$/, 'Project quality plan (version $1, $2)'],
  [/^沟通计划（第 (\d+) 版）$/, 'Communication plan (version $1)'],
  [/^(\d+)\. (.+?) · (未开始|进行中|已关闭)$/, '$1. $2 · $3'],
  [/^未关闭问题 \/ 行动项 (\d+) 个（逾期 (\d+) 个）；未关闭风险 \/ 机会 (\d+) 个$/, 'Open issues / actions $1 ($2 overdue); open risks / opportunities $3'],
  [/^(\d+) 个（逾期 (\d+) 个）$/, '$1 (overdue $2)'],
  [/^(\d+) 个$/, '$1'],
  [/^v(\d+)$/, 'v$1'],
  [/^预计完工 (\S+) 晚于计划 (\S+)$/, 'Projected finish $1 is later than planned $2'],
  [/^预计成本超出预算$/, 'Projected cost exceeds budget'],
  [/^(\d+) 个严重不符合项未关闭$/, '$1 critical nonconformities open'],
  [/^(\d+) 个重大不符合项未关闭$/, '$1 major nonconformities open'],
  [/^进度落后 (\d+) 个百分点$/, 'Behind schedule by $1 percentage points'],
  [/^(\d+) 个行动项逾期$/, '$1 overdue actions'],
  [/^(\d+) 个高分风险$/, '$1 high-score risks'],
  [/^项目评审逾期$/, 'Project review overdue'],
  [/^(\d+) 个成本科目预计超支$/, '$1 cost accounts projected to overrun'],
  [/^待审批变更 (\S+)：(.+)$/, 'Change $1 awaiting approval: $2'],
  [/^有一个进行中的关口评审待记录结论$/, 'A gate review is waiting for a decision'],
  [/^(问题|行动项)：(.+)$/, '$1: $2'],
  [/^执行纠正措施 (\S+)：(.+)$/, 'Carry out corrective action $1: $2'],
  [/^工作包 (\S+) (.+?)（(\d+)%）$/, 'Work package $1 $2 ($3%)'],
  [/^培训：(.+)$/, 'Training: $1'],
];
